import React, { createContext, useContext, useState, useEffect } from 'react';

// Translation objects
const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    products: 'Products',
    inventory: 'Inventory',
    purchases: 'Purchases',
    sales: 'Sales',
    clients: 'Clients',
    suppliers: 'Suppliers',
    fixedAssets: 'Fixed Assets',
    investments: 'Investments',
    prepaidExpenses: 'Prepaid Expenses',
    payments: 'Payments',
    cashRegister: 'Cash Register',
    adjustments: 'Adjustments',
    reports: 'Reports',
    
    // Common Actions
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    print: 'Print',
    close: 'Close',
    submit: 'Submit',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    
    // Common Fields
    code: 'Code',
    name: 'Name',
    phone: 'Phone',
    address: 'Address',
    notes: 'Notes',
    
    // Dashboard
    totalSales: 'Total Sales',
    totalClients: 'Total Clients',
    totalPurchases: 'Total Purchases',
    netRevenue: 'Net Revenue',
    profit: 'Profit',
    loss: 'Loss',
    lowStockAlert: 'Low Stock Alert',
    recentSales: 'Recent Sales',
    recentPurchases: 'Recent Purchases',
    unpaidSales: 'Unpaid Sales',
    unpaidPurchases: 'Unpaid Purchases',
    totalProducts: 'Total Products',
    activeProducts: 'Active Products',
    loadingDashboard: 'Loading dashboard...',
    noSalesYet: 'No sales yet',
    noPurchasesYet: 'No purchases yet',
    
    // Inventory
    inventorySheet: 'Inventory Sheet',
    trackPurchasesAndSales: 'Track purchases and sales of goods',
    exportToExcel: 'Export to Excel',
    startDate: 'Start Date',
    endDate: 'End Date',
    productFilter: 'Product Filter',
    allProducts: 'All Products',
    searchProduct: 'Search Product',
    registrationNo: 'Registration No.',
    rncSupplier: 'RNC Supplier',
    operation: 'Operation',
    amountInAmount: 'Amount in Amount',
    balanceInAmount: 'Balance in Amount',
    balanceIn: 'Balance in',
    balanceInQuantity: 'Balance in Quantity',
    averageUnitCost: 'Average Unit Cost',
    year: 'Year',
    month: 'Month',
    currentBalance: 'Current Balance',
    averageCost: 'Average Cost',
    totalIncome: 'Total Income',
    totalCost: 'Total Cost',
    grossMargin: 'Gross Margin',
    grossMarginPercent: '% Gross Margin',
    grossMarginOnRevenue: '% Gross Margin on Revenue',
    grossMarginOnCost: '% Gross Margin on Cost',
    noInventoryMovements: 'No inventory movements found for the selected criteria',
    adjustDateRange: 'Try adjusting your date range or product filter',
    
    // Payments
    paymentsManagement: 'Payments Management',
    trackPayments: 'Track payments to suppliers and from clients',
    newPayment: 'New Payment',
    editPayment: 'Edit Payment',
    paymentsOut: 'Payments Out',
    paymentsIn: 'Payments In',
    netCashFlow: 'Net Cash Flow',
    allPaymentTypes: 'All Payment Types',
    paymentOut: 'Payment Out',
    paymentIn: 'Payment In',
    toSuppliers: 'To Suppliers',
    fromClients: 'From Clients',
    paymentOutToSupplier: 'Payment Out (To Supplier)',
    paymentInFromClient: 'Payment In (From Client)',
    invoicesToApply: 'Invoices to which this payment will be applied',
    listOutstandingCredit: 'List outstanding credit invoices',
    listOutstandingCash: 'List outstanding cash invoices',
    invoiceNo: 'Invoice No.',
    balancePending: 'Balance Pending',
    amountToPay: 'Amount to Pay',
    totalAmountToApply: 'Total Amount to Apply',
    
    // Products
    newProduct: 'New Product',
    productCode: 'Product Code',
    productName: 'Product Name',
    description: 'Description',
    unitOfMeasurement: 'Unit of Measurement',
    amount: 'Amount',
    quantity: 'Quantity',
    unitPrice: 'Unit Cost',
    unitCost: 'Unit Cost',
    subtotal: 'Subtotal',
    tax: 'Tax',
    taxRate: 'Tax Rate',
    taxAmount: 'Tax Amount',
    total: 'Total',
    stock: 'Stock',
    category: 'Category',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    price: 'Price',
    salesPrice: 'Sales Price',
    salesPriceHistory: 'Sales Price History',
    priceHistory: 'Price History',
    addNewPrice: 'Add New Price',
    editPrice: 'Edit Price',
    effectiveDate: 'Effective Date',
    syncStatus: 'Sync Status',
    viewSalesPriceHistory: 'View Sales Price History',
    history: 'History',
    noPriceHistoryFound: 'No price history found. Add a new price to get started.',
    priceAddedSuccessfully: 'Price added successfully!',
    priceUpdatedSuccessfully: 'Price updated successfully!',
    priceDeletedSuccessfully: 'Price deleted successfully!',
    deletePriceConfirm: 'Delete this price?',
    priceSyncSuccess: 'Price status synchronized successfully!',
    errorSyncingPrices: 'Error syncing prices',
    errorSavingPrice: 'Error saving price',
    errorDeletingPrice: 'Error deleting price',
    enterSalesPriceAndDate: 'Please enter sales price and effective date',
    update: 'Update',
    
    // Purchase-specific translations
    purchaseDetails: 'Purchase Details',
    productDetails: 'Product Details',
    invoiceSuppliers: 'Invoice Suppliers',
    createNewPurchase: 'Create New Purchase',
    selectProduct: 'Select product...',
    unitCostWithAI: 'Unit Cost with AI',
    addProduct: 'Add Product',
    done: 'Done',
    otherInvoicesAssociated: 'Other Invoices Associated with this Purchase',
    supplierRncShort: "Supplier's RNC",
    taxAmountBase: 'Tax Amount (Base)',
    purchaseOf: 'Purchase of',
    selectType: 'Select type',
    addInvoice: 'Add Invoice',
    noProductsFound: 'No products found',
    noAssociatedInvoicesFound: 'No associated invoices found',
    productsAdded: 'Products Added',
    items: 'items',
    associatedInvoicesCount: 'Associated Invoices',
    invoices: 'invoices',
    productTotal: 'Product Total',
    associatedCosts: 'Associated Costs',
    grandTotal: 'GRAND TOTAL',
    creating: 'Creating...',
    createPurchase: 'Create Purchase',
    goodsForInternalUse: 'Goods for internal use (PPE)',
    investmentsOrCapitalGoods: 'Investments or capital goods',
    servicesOrOther: 'Services or other',
    policiesAndGuarantee: 'Policies and guarantee',
    deposit: 'Deposit',
    includesProportionalShare: 'Includes proportional share of associated costs',
    adjustedUnitCostWithAssociatedCosts: 'Adjusted unit cost with associated costs',
    editable: 'Editable',
    editableTaxAmount: 'Editable tax amount',
    
    // Purchases
    newPurchase: 'New Purchase',
    registrationNumber: 'Registration Number',
    registrationDate: 'Registration Date',
    date: 'Date',
    supplier: 'Supplier',
    supplierRnc: "Supplier's RNC",
    supplierName: 'Supplier Name',
    selectSupplier: 'Select a supplier',
    ncf: 'NCF',
    purchaseType: 'Purchase Type',
    paymentTerms: 'Payment Terms',
    paymentMethod: 'Payment Method',
    paymentStatus: 'Payment Status',
    cash: 'Cash',
    cheque: 'Cheque',
    credit: 'Credit',
    bankTransfer: 'Bank Transfer',
    creditCard: 'Credit Card',
    unpaid: 'Unpaid',
    partial: 'Partial',
    paidAmount: 'Paid Amount',
    balanceDue: 'Balance Due',
    
    // Associated Invoices
    associatedInvoices: 'Other Invoices Associated with this Purchase',
    concept: 'Concept',
    freight: 'Freight',
    customs: 'Customs',
    insurance: 'Insurance',
    handling: 'Handling',
    storage: 'Storage',
    other: 'Other',
    
    // Sales
    newSale: 'New Sale',
    client: 'Client',
    clientRnc: "Client's RNC",
    clientName: 'Client Name',
    selectClient: 'Select a client',
    saleType: 'Sale Type',
    discount: 'Discount',
    newClient: 'New Client',
    editClient: 'Edit Client',
    idTaxNumber: 'ID/Tax Number',
    rncsupplier: 'RNC Supplier',
    
    // Suppliers
    newSupplier: 'New Supplier',
    editSupplier: 'Edit Supplier',
    
    // Forms
    required: 'Required',
    optional: 'Optional',
    enterValue: 'Enter value',
    selectOption: 'Select option',
    
    // Table Headers
    actions: 'Actions',
    viewDetails: 'View Details',
    makePayment: 'Make Payment',
    collectPayment: 'Collect Payment',
    
    // Messages
    successCreate: 'Created successfully',
    successUpdate: 'Updated successfully',
    successDelete: 'Deleted successfully',
    errorCreate: 'Error creating',
    errorUpdate: 'Error updating',
    errorDelete: 'Error deleting',
    confirmDelete: 'Are you sure you want to delete this item?',
    noData: 'No data available',
    loading: 'Loading...',
    
    // Purchase Summary
    purchaseSummary: 'Purchase Summary',
    createSale: 'Create Sale',
    
    // Misc
    show: 'Show',
    hide: 'Hide',
    merchandiseForSale: 'Merchandise for sale or consumption',
    service: 'Service',
    fixedAsset: 'Fixed Asset',
    completed: 'Completed',
    pending: 'Pending',
    cancelled: 'Cancelled',
    saleNumber: 'Sale Number',
    purchaseNumber: 'Purchase Number',
    totalAmount: 'Total Amount',
    paymentAmount: 'Payment Amount',
    paymentType: 'Payment Type',
    addProducts: 'Add Products',
    product: 'Product',
    
    // Payment Alerts and Messages
    noOutstandingInvoicesSupplier: '⚠️ No outstanding invoices found for this supplier.\n\nPossible reasons:\n1. All purchases are paid\n2. Purchases are Cash type (not Credit)\n3. No purchases exist for this supplier',
    noOutstandingInvoicesClient: '⚠️ No outstanding invoices found for this client.\n\nPossible reasons:\n1. All sales are paid\n2. Sales are Cash type (not Credit)\n3. No sales exist for this client',
    errorLoadingInvoices: 'Error loading outstanding invoices. Check console for details.',
    pleaseSelectEntity: 'Please select a supplier or client',
    warningNoInvoices: '⚠️ WARNING: No invoices selected!\n\nThis payment will be recorded but NOT applied to any invoices.\nThe purchase/sale balances will NOT be updated.\n\nDo you want to continue anyway?\n\nClick "Cancel" to go back and select invoices.',
    paymentSavedSuccess: '✅ Payment saved successfully!\n\nApplied to {count} invoice(s).',
    paymentSavedNoInvoices: '⚠️ Payment saved but NOT applied to any invoices.\n\nYou can delete and recreate it with invoice selection.',
    selectSupplierOrClient: 'Select Supplier/Client',
    invoicesToApplyPayment: 'Invoices to which this payment will be applied',
    checkToSelect: 'Check to select invoice',
    totalToApply: 'Total Amount to Apply',
    overpaymentDetected: 'Overpayment Detected',
    overpaymentMessage: 'Payment amount ({payment}) exceeds total applied amount ({applied}). The excess amount of {excess} will be recorded as a credit balance for future use.',
    enterValidAmount: 'Please enter a valid payment amount',
    
    // Accounts Payable & Receivable
    accountsPayable: 'Accounts Payable',
    accountsReceivable: 'Accounts Receivable',
    moneyYouOwe: 'Money you owe (to credit card companies, suppliers on credit, etc.)',
    moneyOwedToYou: 'Money owed to you (from credit card sales, client credits, etc.)',
    received: 'Received',
    balanceYouOwe: 'Balance (You Owe)',
    allStatus: 'All Status',
    supplierCodeAndName: 'Supplier Code and Name',
    purchaseDate: 'Purchase Date',
    paymentDeadline: 'Payment Deadline',
    type: 'Type',
    relatedDocumentNumber: 'Related Document Number',
    balance: 'Balance',
    action: 'Action',
    paid: 'Paid',
    pay: 'Pay',
    unit: 'Unit',
    qty: 'Qty',
    noAccountsPayableFound: 'No accounts payable found',
    noAccountsReceivableFound: 'No accounts receivable found',
    recordPayment: 'Record Payment',
    document: 'Document',
    alreadyPaid: 'Already Paid',
    enterAmount: 'Enter amount',
    confirmPayment: 'Confirm Payment',
    collect: 'Collect',
    clickToEditDeadline: 'Click to edit deadline',
    invalidDate: 'Invalid date',
    pleaseSelectValidDeadline: 'Please select a valid deadline',
    deadlineUpdated: 'Deadline updated',
    paymentDeadlineHasBeenUpdated: 'Payment deadline has been updated',
    
    // Cash Register
    dailyCashManagement: 'Daily cash management and tracking',
    newTransaction: 'New Transaction',
    totalInflow: 'Total Inflow',
    totalOutflow: 'Total Outflow',
    areYouSureDeleteTransaction: 'Are you sure you want to delete this transaction?',
    errorSavingTransaction: 'Error saving transaction',
    errorDeletingTransaction: 'Error deleting transaction',
    noTransactionsFound: 'No transactions found',
    
    // Reports
    businessReports: 'Business Reports',
    analyticsAndInsights: 'Analytics and insights for your business',
    to: 'to',
    salesOverview: 'Sales Overview',
    purchasesOverview: 'Purchases Overview',
    cashFlowOverview: 'Cash Flow Overview',
    inventoryOverview: 'Inventory Overview',
    lowStockProducts: 'Low Stock Products',
    totalInventoryValue: 'Total Inventory Value',
    profitAnalysis: 'Profit Analysis',
    grossProfit: 'Gross Profit',
    quickActions: 'Quick Actions',
    viewInventorySheet: 'View Inventory Sheet',
    viewDetailedInventory: 'View Detailed Inventory',
    viewPaymentsReport: 'View Payments Report',
    viewDetailedPayments: 'View Detailed Payments',
    exportReports: 'Export Reports',
    downloadPDF: 'Download PDF',
    totalRevenue: 'Total Revenue',
    
    // Cash Register specific
    bankDeposit: 'Bank Deposit',
    endOfDayReport: 'End of Day Report',
    recordCashCheckDeposit: 'Record cash/check deposit to bank account',
    cashRegisterName: 'Cash Register Name',
    bankAccountName: 'Bank Account Name',
    bankName: 'Bank Name',
    recordDeposit: 'Record Deposit',
    collectionSummary: 'Collections Summary',
    cashCollections: 'Cash Collections',
    checkCollections: 'Check Collections',
    bankTransfers: 'Bank Transfers',
    bankDeposits: 'Bank Deposits',
    creditCardCollections: 'Credit Card Collections',
    totalCollections: 'TOTAL COLLECTIONS',
    mainCashRegister: 'Main Cash Register',
    businessCheckingAccount: 'Business Checking Account',
    dailyCashDeposit: 'Daily cash deposit',
    transactionType: 'Transaction Type',
    relatedDocType: 'Related Document Type',
    documentNumber: 'Document Number',
    clientRncCedula: 'Client RNC/Cedula',
    newCashTransaction: 'New Cash Transaction',
    registrationHash: 'Registration #',
    source: 'Source',
    docNumber: 'Doc #',
    bankAccount: 'Bank Account',
    originalType: 'Original Type',
    method: 'Method',
    allTransactions: 'All Transactions',
    inflowMoneyIn: 'Inflow (Money In)',
    outflowMoneyOut: 'Outflow (Money Out)',
    searchTransactions: 'Search transactions...',
    inflow: 'Inflow',
    outflow: 'Outflow',
    debitCard: 'Debit Card',
    check: 'Check',
    
    // Bank Register specific
    bankRegister: 'Bank Register',
    currentBankBalance: 'Current Bank Balance',
    newBankTransaction: 'New Bank Transaction',
    bankAccountTransactions: 'Track bank account transactions (transfers and deposits)',
    accountNumber: 'Account Number',
    referenceNumber: 'Reference Number',
    describeTransaction: 'Describe the transaction...',
    createTransaction: 'Create Transaction',
    cashInflows: 'Cash Received (Sales, etc.)',
    cashOutflows: 'Cash Paid Out (Purchases, Expenses)',
    expectedCashInRegister: 'Expected Cash in Register',
    openingBalance: 'Opening Balance',
    closingBalance: 'Closing Balance',
    cashIn: 'Cash In',
    depositIn: 'Deposit In',
    bankTransferIn: 'Bank Transfer In',
    cashOut: 'Cash Out',
    depositOut: 'Deposit Out',
    bankTransferOut: 'Bank Transfer Out',
    totalIn: 'Total In',
    totalOut: 'Total Out',
    partyEntity: 'Party/Entity',
    clientSupplierBank: 'Client/Supplier/Bank',
    cost: 'Cost',
    costOfGoodsSold: 'Cost of Goods Sold',
    
    // Phase 1 - Master Data
    bankAccounts: 'Bank Accounts',
    newBankAccount: 'New Bank Account',
    editBankAccount: 'Edit Bank Account',
    accountType: 'Account Type',
    checking: 'Current',
    savings: 'Savings',
    location: 'Location',
    cashRegisters: 'Cash Registers',
    newCashRegister: 'New Cash Register',
    editCashRegister: 'Edit Cash Register',
    cards: 'Cards',
    newCard: 'New Card',
    editCard: 'Edit Card',
    cardNumber: 'Card Number',
    last4Digits: 'Last 4 Digits',
    cardType: 'Card Type',
    cardBrand: 'Card Brand',
    cardName: 'Card Name',
    financers: 'Financers',
    financersDesc: 'Manage investors and financing sources',
    newFinancer: 'New Financer',
    editFinancer: 'Edit Financer',
    contactPerson: 'Contact Person',
    email: 'Email',
    financerType: 'Financer Type',
    bank: 'Bank',
    investor: 'Investor',
    rnc: 'RNC',
    create: 'Create',
    
    // Phase 3 - Cash Register Updates
    selectCashRegister: 'Select Cash Register',
    selectBankAccount: 'Select Bank Account',
    selectCustomer: 'Select Customer',
    selectFinancer: 'Select Financer',
    selectContributor: 'Select Contributor',
    selectLender: 'Select Lender',
    selectInvoices: 'Select Invoices',
    arCollection: 'AR Collection',
    contribution: 'Contribution',
    loan: 'Loan',
    correction: 'Correction',
    chequeNumber: 'Cheque Number',
    receiptNumber: 'Receipt Number',
    bankCheque: 'Bank Cheque',
    pendingInvoices: 'Pending Invoices',
    transactionCreated: 'Transaction created successfully!',
    corrections: 'Corrections',
    sale: 'Sale',
    netCashPosition: 'Net Cash Position',
    
    // Phase 4 - Bank Register Updates
    chequeTransferNumber: 'Cheque/Transfer #',
    selectInvoicesToPay: 'Select Invoices to Pay',
    selectedInvoicesTotal: 'Selected Invoices Total',
    noPendingInvoicesForSupplier: 'No pending invoices found for this supplier',
    
    // Missing Bank Register translations
    fromAccountsPayable: 'From Accounts Payable',
    creditPurchasePayment: 'Credit Purchase Payment',
    thisTransactionWillPay: 'This transaction will pay the credit purchase debt. The form has been pre-filled with the payment details.',
    pleaseKeepTransactionType: 'Please keep Transaction Type as "OUTFLOW" for payment.',
    pleaseSelectAtLeastOneInvoice: 'Please select at least one invoice to pay',
    deleteTransactionConfirm: 'Are you sure you want to delete this transaction?',
    selectSpecificInvoices: 'Select the specific invoices/purchases you want to pay. Each item shows detailed invoice information.',
    invoice: 'invoice',
    invoicesLowercase: 'invoices',
    paymentColon: 'Payment:',
    all: 'All',
    // Missing AccountsPayable translations
    payableTo: 'Payable To',
    cardCompany: 'Card Company',
    loadingAccountsPayable: 'Loading accounts payable',
    pleaseSelectCardForPayment: 'Please select a card for payment',
    paymentRecordedSuccessfully: 'Payment recorded successfully',
    recordingPayment: 'Recording payment',
    updatingDeadline: 'Updating deadline',
    paymentForCreditPurchase: 'Payment for Credit Purchase',
    creditPurchasePaymentType: 'Credit Purchase Payment',
    payViaBankButton: 'Pay via Bank',
    
    // Missing AccountsPayable translations
    selectDebitCard: 'Select Debit Card',
    immediatePayment: 'Immediate Payment',
    selectADebitCard: 'Select a debit card...',
    debitCardExplanation: 'DEBIT card: Money deducted from bank immediately to pay this debt',
    creditCardPayment: 'Credit Card Payment',
    cardLabel: 'Card:',
    whatHappens: 'What happens:',
    creditLimitRestored: 'Credit limit will be restored by',
    noCardSelectionNeeded: 'No card selection needed - the system will automatically use the original credit card.',
    confirmPaymentRestoreCredit: 'Confirm Payment & Restore Credit',
    
    // Additional missing translations
    saleDetails: 'Sale Details',
    processCardPayment: 'Process Card Payment',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    editNetwork: 'Edit Network',
    deleteNetwork: 'Delete Network',
    viewDepreciationSchedule: 'View Depreciation Schedule',
    ncfNumber: 'NCF Number',
    unitCostPlaceholder: 'Unit Cost',
    allTypes: 'All Types',
    debitNote: 'Debit Note',
    creditNote: 'Credit Note',
    adjustment: 'Adjustment',
    debitNoteND: 'Debit Note (ND)',
    creditNoteNC: 'Credit Note (NC)',
    adjustmentAJ: 'Adjustment (AJ)',
    creditSaleCollection: 'Credit Sale Collection',

    // ✅ Module Navigation & Sidebar
    backToDashboard: 'Back to Dashboard',
    favorites: 'Favorites',
    hidden: 'Hidden',
    resetToDefault: 'Reset to Default',
    customizeMenu: 'Customize menu',
    doneCustomizing: 'Done customizing',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    addToFavorites: 'Add to favorites',
    removeFromFavorites: 'Remove from favorites',
    resetMenuConfirm: 'Reset menu to default layout?',
    noItemsAvailable: 'No items available',

    // ✅ Module Names
    masterData: 'Master Data',
    masterDataDesc: 'Configure your business data',
    masterDataTitle: 'Master Data Management',
    masterDataSubtitle: 'Configure and manage your core business data. Select an option from the sidebar to get started.',

    transactionsModule: 'Transactions',
    transactionsDesc: 'Manage daily operations',
    transactionsTitle: 'Transaction Management',
    transactionsSubtitle: 'Record and manage all your business transactions. Select an option from the sidebar to get started.',

    expensesModule: 'Expenses',
    expensesDesc: 'Track and manage expenses',
    expensesTitle: 'Expense Management',
    expensesSubtitle: 'Track and manage all your business expenses. Select an option from the sidebar to get started.',

    accountingModule: 'Accounting',
    accountingDesc: 'Financial management & reporting',
    accountingTitle: 'Accounting & Financial Management',
    accountingSubtitle: 'Manage your financial records and generate reports. Select an option from the sidebar to get started.',

    assetsModule: 'Assets & Financing',
    assetsDesc: 'Manage assets and investments',
    assetsTitle: 'Assets & Financing Management',
    assetsSubtitle: 'Manage fixed assets, investments, financing, and generate asset reports. Select an option from the sidebar to get started.',

    administrationModule: 'Administration',
    administrationDesc: 'System management & security',
    administrationTitle: 'System Administration',
    administrationSubtitleAdmin: 'Manage users, roles, permissions, and system configuration. Select an option from the sidebar to get started.',
    administrationSubtitleUser: 'Manage data classification and transaction deletion requests. Select an option from the sidebar to get started.',

    reportsModule: 'Reports',
    reportsDesc: 'Business intelligence & analytics',
    reportsTitle: 'Reports & Analytics',
    reportsSubtitle: 'Generate business intelligence reports and analytics. Select an option from the sidebar to get started.',

    // ✅ Module Dashboard
    welcomeTitle: 'Welcome to Your ERP System',
    welcomeSubtitle: 'Select a module to get started with your business operations',
    welcomeCustomizing: 'Drag modules to reorder • Click eye icon to hide • Click again to save',
    customizeDashboard: 'Customize Dashboard',
    doneCustomizingDashboard: 'Done Customizing',
    hiddenModules: 'Hidden Modules',
    resetDashboardConfirm: 'Reset dashboard to default layout?',

    // ✅ Authentication
    auth_loginTitle: 'Welcome Back',
    auth_loginSubtitle: 'Sign in to your ERP account',
    auth_registerTitle: 'Create Your Account',
    auth_registerSubtitle: 'Join our ERP system',
    auth_noAccount: "Don't have an account?",
    auth_haveAccount: 'Already have an account?',

    // ✅ Validation Messages
    validation_fillAllFields: 'Please fill in all fields',
    validation_fillRequired: 'Please fill in all required fields',
    validation_selectSupplier: 'Please select a supplier',
    validation_selectCard: 'Please select a card',
    validation_validAmount: 'Please enter a valid payment amount',
    validation_validAmountGreaterZero: 'Please enter a valid amount greater than zero',
    validation_amountExceedsSale: 'Payment amount cannot exceed sale amount',
    validation_amountExceedsUsed: 'Amount cannot exceed used credit of $',
    validation_selectBankAccount: 'Please select a bank account',
    validation_selectBankForMethod: 'Please select a bank account for this payment method',
    validation_selectCardPayment: 'Please select a credit card to pay with',
    validation_selectCategory: 'Please select an expense category',
    validation_selectType: 'Please select an expense type',
    validation_amountGreaterThanZero: 'Payment amount must be greater than 0',
    validation_fillChequeDetails: 'Please fill in cheque number and date',
    validation_fillTransferDetails: 'Please fill in transfer number and date',
    validation_fillCardDetails: 'Please fill in all card payment details',
    validation_enterCheckNumber: 'Please enter a check number',
    validation_selectBankAccountRestore: 'Please select a bank account',

    // ✅ Labels
    labels_emailAddress: 'Email Address',
    labels_password: 'Password',
    labels_rememberMe: 'Remember me',
    labels_firstName: 'First Name',
    labels_lastName: 'Last Name',
    labels_role: 'Role',
    labels_saleDetails: 'Sale Details',
    labels_saleNumber: 'Sale Number:',
    labels_amountDue: 'Amount Due:',
    labels_cardType: 'Type:',
    labels_bank: 'Bank:',
    labels_creditLimit: 'Credit Limit:',
    labels_availableLimit: 'Available:',
    labels_creditCardAutoSelected: 'Credit Card (Auto-Selected)',
    labels_selectCreditCard: 'Select Credit Card to Pay With',
    labels_customer: 'Customer:',
    labels_paymentAmount: 'Payment Amount:',
    labels_paymentMethod: 'Payment Method:',
    labels_invoices: 'Invoices:',
    labels_cashRegister: 'Cash Register:',
    labels_bankAccount: 'Bank Account:',
    labels_error: 'Error',
    labels_availableCredit: 'Available Credit:',
    labels_creditWillBeUsed: 'Credit Will Be Used:',
    labels_invoiceBalance: 'Invoice Balance:',
    labels_cashPaymentNeeded: 'Cash Payment Needed:',
    labels_selectedMethod: 'Selected Payment Method:',
    labels_creditOnly: 'Credit-Only Payment',
    labels_paymentNotAllowed: 'Payment Not Allowed',
    labels_maximum: 'Maximum: $',
    labels_currentUsedCredit: '(current used credit)',
    labels_supplier: 'Supplier',
    labels_usedCredit: 'Used Credit',
    labels_selectDebitCard: 'Select Debit Card',
    labels_card: 'Card',
    labels_available: 'Available: ₹',
    labels_required: 'Required: ₹',
    labels_approvalRoleLimit: 'Approval Role & Limit',

    // ✅ Links
    links_forgotPassword: 'Forgot your password?',
    links_termsOfService: 'Terms of Service',

    // ✅ Buttons
    buttons_signIn: 'Sign in',
    buttons_signUp: 'Sign up',
    buttons_cancel: 'Cancel',
    buttons_processPayment: 'Process Payment',
    buttons_processCreditPayment: 'Process Credit Payment',
    buttons_restoreCredit: 'Restore Credit',
    buttons_logout: 'Logout',
    buttons_edit: 'Edit',
    buttons_delete: 'Delete',
    buttons_firstPage: 'First Page',
    buttons_previousPage: 'Previous Page',
    buttons_nextPage: 'Next Page',
    buttons_lastPage: 'Last Page',
    buttons_removeFromFavorites: 'Remove from favorites',
    buttons_addToFavorites: 'Add to favorites',
    buttons_hideMenuItem: 'Hide this menu item',
    buttons_createAccount: 'Create Account',

    // ✅ States/Loading
    states_signingIn: 'Signing in...',
    states_creatingAccount: 'Creating account...',
    states_calculating: 'Calculating optimal payment strategy...',
    states_processing: 'Processing...',
    states_restoring: 'Restoring...',
    states_loading: 'Loading...',

    // ✅ Messages
    messages_featureComingSoon: 'Forgot password functionality coming soon!',
    messages_creditOnlyExplanation: "This payment will be processed entirely using the customer's existing credit balance. No payment method or cash register selection is required.",
    messages_paymentSuccess: 'Payment processed successfully',
    messages_cardPaymentSuccess: 'Card payment processed successfully!',
    messages_creditOnlyPaymentSuccess: 'Payment processed successfully using credit balance',

    // ✅ Errors
    errors_loadCards: 'Failed to load available cards',
    errors_processPayment: 'Error processing payment',
    errors_failedProcessCardPayment: 'Failed to process card payment',
    errors_restoreCard: 'Failed to restore credit card. Please try again.',
    errors_insufficientBalance: 'Insufficient balance in',
    errors_insufficientCreditLimit: 'Insufficient credit limit on',
    errors_createExpense: 'Error creating expense',

    // ✅ Placeholders
    placeholders_enterEmail: 'Enter your email',
    placeholders_enterPassword: 'Enter your password',
    placeholders_exampleFirstName: 'John',
    placeholders_exampleLastName: 'Doe',
    placeholders_exampleEmail: 'john.doe@example.com',
    placeholders_confirmPassword: 'Confirm your password',
    placeholders_amount: '0.00',
    placeholders_paymentDescription: 'Payment description...',
    placeholders_enterAmount: 'Enter payment amount',
    placeholders_checkReference: 'Check number, transfer ID, or reference',
    placeholders_paymentNotes: 'Additional notes about this payment',
    placeholders_expenseDescription: 'Brief description of the expense...',
    placeholders_checkNumber: 'Enter check number',
    placeholders_transferReference: 'Enter transfer reference',
    placeholders_transactionReference: 'Transaction ID or reference',
    placeholders_selectPaymentType: 'Select payment type...',
    placeholders_selectSupplier: 'Select supplier...',
    placeholders_selectClient: 'Select client...',
    placeholders_selectCard: 'Select card...',
    placeholders_selectBankAccount: 'Select bank account...',
    placeholders_searchTypes: 'Search expense types...',
    placeholders_searchCategories: 'Search categories...',
    placeholders_referenceNumber: 'Optional reference number',
    placeholders_notes: 'Optional notes about this restoration',
    placeholders_voucherNumber: 'Enter voucher/authorization number',

    // ✅ Options/Dropdowns
    options_selectCard: 'Choose a card...',
    options_selectAll: 'All',
    options_credit: 'Credit (Pay Later)',
    options_cash: 'Cash',
    options_bankTransfer: 'Bank Transfer',
    options_cheque: 'Cheque',
    options_check: 'Check',
    options_debitCard: 'Debit Card (Immediate)',
    options_creditCard: 'Credit Card (Creates Payable)',
    options_servicesOther: 'Services or Other',
    options_prepaidExpenses: 'Prepaid Expenses',
    options_policiesGuarantee: 'Policies and Guarantee',

    // ✅ Option Groups
    optgroups_bankPayments: 'Bank Payments (Immediate)',
    optgroups_cardPayments: 'Card Payments',

    // ✅ Sections/Headings
    sections_creditAnalysis: 'Customer Credit Balance Analysis',
    sections_paymentBreakdown: 'Payment Breakdown',
    sections_registerConfig: 'Cash Register Payment Configuration',

    // ✅ Payment Items
    payments_fromCredit: 'From Customer Credit Balance',
    payments_cashRequired: 'Cash Payment Required',
    payments_newCredit: 'New Credit Balance',

    // ✅ Modal Titles
    modals_cardPaymentTitle: 'Process Card Payment',
    modals_creditPaymentTitle: 'Smart Customer Payment with Credit Balance',
    modals_restoreCardTitle: 'Restore Credit Card',

    // ✅ Accessibility
    aria_selectExpenseType: 'Select expense type',
    aria_selectExpenseCategory: 'Select expense category',

    // ✅ Hints/Tips
    hints_dragReorder: 'Drag to reorder',

    // ✅ Pagination
    pagination_ellipsis: '...',

    // 🆕 Toast Messages
    pleaseAddAtLeastOneProduct: 'Please add at least one product for goods purchase',
    enterSupplierRncNameTax: 'Please enter Supplier RNC, Supplier Name, and Tax Amount',
    selectPaymentTypeInvoice: 'Please select a payment type for the invoice',
    selectCardForPaymentType: 'Please select a card for the selected payment type',
    selectBankAccountForPaymentType: 'Please select a bank account for the selected payment type',
    selectProductValidQuantityCost: 'Please select a product and enter valid quantity and unit cost',
    paymentDeletedSuccess: 'Payment deleted successfully',
    investmentMarkedPaidSuccess: 'Investment marked as paid successfully',
    failedMarkInvestmentPaid: 'Failed to mark investment as paid',
    paymentUpdatedSuccess: 'Payment updated successfully',
    failedUpdatePayment: 'Failed to update payment',
    failedFixInvestmentStatus: 'Failed to fix investment status',
    investmentAgreementCreatedSuccess: 'Investment agreement created successfully',
    failedCleanupAccountsPayable: 'Failed to cleanup AccountsPayable entries',
    financerUpdatedSuccess: 'Financer updated successfully',
    financerCreatedSuccess: 'Financer created successfully',
    financerDeletedSuccess: 'Financer deleted successfully',
    categoryNameRequired: 'Category name is required',
    categoryCodeRequired: 'Category code is required',
    categoryUpdatedSuccess: 'Category updated successfully',
    categoryCreatedSuccess: 'Category created successfully',
    typeNameRequired: 'Type name is required',
    typeCodeRequired: 'Type code is required',
    expenseTypeAddedSuccess: 'Expense type added successfully',
    categoryDeletedSuccess: 'Category deleted successfully',
    cashRegisterUpdatedSuccess: 'Cash register updated successfully',
    cashRegisterCreatedSuccess: 'Cash register created successfully',
    cashRegisterDeletedSuccess: 'Cash register deleted successfully',
    failedLoadDashboardData: 'Failed to load dashboard data',
    failedLoadExpiringData: 'Failed to load expiring data',
    failedLoadClassifications: 'Failed to load classifications',
    complianceReportDownloadedSuccess: 'Compliance report downloaded successfully',
    failedDownloadReport: 'Failed to download report',
    selectPaymentMethod: 'Please select a payment method',
    selectCashRegisterForCash: 'Please select a cash register for cash payments',
    selectBankAccountForBank: 'Please select a bank account for bank payments',
    selectInvestmentLoanAgreement: 'Please select an investment/loan agreement',
    selectDebitCardNetwork: 'Please select a debit card payment network',
    excelExportFunctionality: 'Excel export functionality would be implemented here',
    pleaseSelectSupplier: 'Please select a supplier',
    fillChequeNumberDate: 'Please fill in cheque number and date',
    fillTransferNumberDate: 'Please fill in transfer number and date',
    fillAllCardPaymentDetails: 'Please fill in all card payment details',
    forgotPasswordComingSoon: 'Forgot password functionality coming soon!',
    paymentCompletedSuccessfully: 'Payment completed successfully! The Accounts Payable status has been updated.',
    transactionCreatedSuccessfully: 'Transaction created successfully!',
    smartPaymentCompletedSuccess: 'Smart payment completed successfully! Credit balances were automatically applied.',
    smartPaymentCompleted: 'Smart payment completed successfully!',
    areYouSureDeleteSupplier: 'Are you sure you want to delete this supplier?',
    createDefaultChartOfAccounts: 'This will create default Chart of Accounts. Continue?',
    resetDashboardToDefault: 'Reset dashboard to default layout?',

    // 🆕 Form Labels
    paymentReferenceRequired: 'Payment Reference *',
    enterPaymentReferenceVoucher: 'Enter payment reference/voucher number',
    voucherDateRequired: 'Voucher Date *',
    chequeNumberRequired: 'Cheque Number *',
    enterChequeNumber: 'Enter cheque number',
    chequeDateRequired: 'Cheque Date *',
    transferNumberRequired: 'Transfer Number *',
    enterTransferReferenceNumber: 'Enter transfer reference number',
    transferDateRequired: 'Transfer Date *',
    searchSuppliers: 'Search suppliers...',
    loadingSuppliers: 'Loading suppliers...',

    // 🆕 Common UI
    loadingData: 'Loading data...',
    loadingPage: 'Loading page...',
    view: 'View',
    download: 'Download',
    upload: 'Upload',
    refresh: 'Refresh',
    reset: 'Reset',
    apply: 'Apply',
    clear: 'Clear',
    from: 'From',
    dateRange: 'Date Range',
    selectDate: 'Select Date',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    showing: 'Showing',
    of: 'of',
    entries: 'entries',
    page: 'Page',
    rowsPerPage: 'Rows per page',
    areYouSure: 'Are you sure?',
    thisActionCannotBeUndone: 'This action cannot be undone',
    confirmAction: 'Confirm Action',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',

    // 🆕 User Role Management
    userRoleManagement: 'User Role Management',
    loadingUserRoles: 'Loading user roles...',
    syncAllAdminManagerRoles: 'Sync All Admin/Manager Roles',
    assignRole: 'Assign Role',
    totalUsers: 'Total Users',
    emailHeader: 'Email',
    fullNameHeader: 'Full Name',
    basicRoleHeader: 'Basic Role',
    approvalRoleHeader: 'Approval Role',
    approvalLimitHeader: 'Approval Limit',
    canDelegateHeader: 'Can Delegate',
    assignedAtHeader: 'Assigned At',
    actionsHeader: 'Actions',
    notSyncedYet: 'Not synced yet',
    yesLabel: 'Yes',
    noLabel: 'No',
    editApprovalLimit: 'Edit Approval Limit',
    removeRole: 'Remove Role',
    assignRoleToUser: 'Assign Role to User',
    userEmailRequired: 'User Email *',
    searchByEmailOrName: 'Search by email or name...',
    roleRequired: 'Role *',
    selectARole: 'Select a role...',
    customApprovalLimit: 'Custom Approval Limit (Optional)',
    leaveEmptyForDefault: 'Leave empty to use default limit',
    canDelegateApproval: 'Can delegate approval to others',
    assigning: 'Assigning...',
    assignRoleButton: 'Assign Role',
    updateApprovalLimit: 'Update Approval Limit',
    userLabel: 'User',
    currentLimit: 'Current Limit',
    newApprovalLimitRequired: 'New Approval Limit *',
    enterNewLimit: 'Enter new approval limit',
    reasonForChangeRequired: 'Reason for Change *',
    explainWhyChanging: 'Explain why you are changing this limit...',
    updating: 'Updating...',
    updateLimitButton: 'Update Limit',
    roleAssignedSuccess: 'Role assigned successfully!',
    approvalLimitUpdatedSuccess: 'Approval limit updated successfully!',
    enterReasonForRemoving: 'Enter reason for removing role from',
    roleRemovedSuccess: 'Role removed successfully!',
    syncConfirmation: 'This will sync all admin and manager users with their approval roles. Continue?',
    syncCompletedSuccess: 'Sync completed successfully!',
    syncedLabel: 'Synced',
    skippedLabel: 'Skipped',
    errorsLabel: 'Errors',

    // 🆕 Fixed Assets
    newFixedAsset: 'New Fixed Asset',
    managePropertyPlantEquipment: 'Manage property, plant, and equipment',

    // 🆕 Adjustments
    newAdjustment: 'New Adjustment',
    editAdjustment: 'Edit Adjustment',
    adjustmentAmountMustBeGreaterThanZero: 'Adjustment amount must be greater than 0. Please add products or enter an amount.',

    // 🆕 Additional Pages
    newExpense: 'New Expense',
    newPrepaidExpense: 'New Prepaid Expense',
    newInvestment: 'New Investment',
    
    // Business Expenses
    businessExpenses: 'Business Expenses',
    
    // Prepaid Expenses
    prepaidExpensesDesc: 'Track advance payments and automatic amortization',
    totalPrepaid: 'Total Prepaid',
    totalAmortized: 'Total Amortized',
    remainingBalance: 'Remaining Balance',
    openingBalanceEntries: 'Opening Balance Entries',
    configuration: 'Configuration',
    
    // Investments
    investmentsDesc: 'Track investments, bonds, and capital goods',
    totalAcquisitionCost: 'Total Acquisition Cost',
    currentValue: 'Current Value',
    totalInvestment: 'Total Investment',
    
    // Investment Agreements
    investmentAgreementsDesc: 'Manage investment and loan agreements before receiving money',
    totalAgreements: 'Total Agreements',
    totalCommitted: 'Total Committed',
    newAgreement: 'New Agreement',
    
    // Investors
    investorsDesc: 'Manage and track all investor investments',
    totalInvestors: 'Total Investors',
    totalInvested: 'Total Invested',
    
    // Investment Report
    investmentReportDesc: 'Portfolio Performance & ROI Analysis',
    
    // General Ledger
    generalLedgerDesc: 'Complete transaction history',
    
    // Opening Balance
    openingBalanceDesc: 'Set initial account balances for your accounting system',
    addEntry: 'Add Entry',
    
    // Placeholders
    placeholders_searchExpenses: 'Search expenses...',
    placeholders_searchPrepaid: 'Search by code, name, type...',
    placeholders_searchInvestments: 'Search investments...',
    
    // Buttons
    buttons_refresh: 'Refresh',
  },
  
  es: {
    // Navegación
    dashboard: 'Panel',
    products: 'Productos',
    inventory: 'Inventario',
    purchases: 'Compras',
    sales: 'Ventas',
    clients: 'Clientes',
    suppliers: 'Proveedores',
    fixedAssets: 'Activos Fijos',
    investments: 'Inversiones',
    prepaidExpenses: 'Gastos Prepagados',
    payments: 'Pagos',
    cashRegister: 'Caja',
    adjustments: 'Ajustes',
    reports: 'Reportes',
    
    // Acciones Comunes
    add: 'Agregar',
    edit: 'Editar',
    delete: 'Eliminar',
    save: 'Guardar',
    cancel: 'Cancelar',
    search: 'Buscar',
    filter: 'Filtrar',
    export: 'Exportar',
    import: 'Importar',
    print: 'Imprimir',
    close: 'Cerrar',
    submit: 'Enviar',
    confirm: 'Confirmar',
    back: 'Atrás',
    next: 'Siguiente',
    
    // Campos Comunes
    code: 'Código',
    name: 'Nombre',
    phone: 'Teléfono',
    address: 'Dirección',
    notes: 'Notas',
    
    // Panel
    totalSales: 'Total de Ventas',
    totalClients: 'Total de Clientes',
    totalPurchases: 'Total de Compras',
    netRevenue: 'Ingresos Netos',
    profit: 'Ganancia',
    loss: 'Pérdida',
    lowStockAlert: 'Alerta de Stock Bajo',
    recentSales: 'Ventas Recientes',
    recentPurchases: 'Compras Recientes',
    unpaidSales: 'Ventas No Pagadas',
    unpaidPurchases: 'Compras No Pagadas',
    totalProducts: 'Total de Productos',
    activeProducts: 'Productos Activos',
    loadingDashboard: 'Cargando panel...',
    noSalesYet: 'Aún no hay ventas',
    noPurchasesYet: 'Aún no hay compras',
    
    // Inventario
    inventorySheet: 'Hoja de Inventario',
    trackPurchasesAndSales: 'Seguimiento de compras y ventas de mercancías',
    exportToExcel: 'Exportar a Excel',
    startDate: 'Fecha de Inicio',
    endDate: 'Fecha de Fin',
    productFilter: 'Filtro de Producto',
    allProducts: 'Todos los Productos',
    searchProduct: 'Buscar Producto',
    registrationNo: 'Número de Registro',
    rncSupplier: 'RNC Proveedor',
    operation: 'Operación',
    amountInAmount: 'Cantidad en Monto',
    balanceInAmount: 'Saldo en Monto',
    balanceIn: 'Saldo en',
    balanceInQuantity: 'Saldo en Cantidad',
    averageUnitCost: 'Costo Unitario Promedio',
    year: 'Año',
    month: 'Mes',
    currentBalance: 'Saldo Actual',
    averageCost: 'Costo Promedio',
    totalIncome: 'Ingresos Totales',
    totalCost: 'Costo Total',
    grossMargin: 'Margen Bruto',
    grossMarginPercent: '% Margen Bruto',
    grossMarginOnRevenue: '% Margen Bruto sobre Ingresos',
    grossMarginOnCost: '% Margen Bruto sobre Costo',
    noInventoryMovements: 'No se encontraron movimientos de inventario para los criterios seleccionados',
    adjustDateRange: 'Intente ajustar su rango de fechas o filtro de producto',
    
    // Pagos
    paymentsManagement: 'Gestión de Pagos',
    trackPayments: 'Seguimiento de pagos a proveedores y de clientes',
    newPayment: 'Nuevo Pago',
    editPayment: 'Editar Pago',
    paymentsOut: 'Pagos Salientes',
    paymentsIn: 'Pagos Entrantes',
    netCashFlow: 'Flujo de Caja Neto',
    allPaymentTypes: 'Todos los Tipos de Pago',
    paymentOut: 'Pago Saliente',
    paymentIn: 'Pago Entrante',
    toSuppliers: 'A Proveedores',
    fromClients: 'De Clientes',
    paymentOutToSupplier: 'Pago Saliente (A Proveedor)',
    paymentInFromClient: 'Pago Entrante (De Cliente)',
    invoicesToApply: 'Facturas a las que se aplicará este pago',
    listOutstandingCredit: 'Listar facturas de crédito pendientes',
    listOutstandingCash: 'Listar facturas de efectivo pendientes',
    invoiceNo: 'Número de Factura',
    balancePending: 'Saldo Pendiente',
    amountToPay: 'Monto a Pagar',
    totalAmountToApply: 'Monto Total a Aplicar',
    
    // Productos
    newProduct: 'Nuevo Producto',
    productCode: 'Código de Producto',
    productName: 'Nombre del Producto',
    description: 'Descripción',
    unitOfMeasurement: 'Unidad de Medida',
    amount: 'Cantidad',
    quantity: 'Cantidad',
    unitPrice: 'Costo Unitario',
    unitCost: 'Costo Unitario',
    subtotal: 'Subtotal',
    tax: 'Impuesto',
    taxRate: 'Tasa de Impuesto',
    taxAmount: 'Monto de Impuesto',
    total: 'Total',
    stock: 'Existencia',
    category: 'Categoría',
    status: 'Estado',
    active: 'Activo',
    inactive: 'Inactivo',
    price: 'Precio',
    salesPrice: 'Precio de Venta',
    salesPriceHistory: 'Historial de Precio de Venta',
    priceHistory: 'Historial de Precios',
    addNewPrice: 'Agregar Nuevo Precio',
    editPrice: 'Editar Precio',
    effectiveDate: 'Fecha Efectiva',
    syncStatus: 'Sincronizar Estado',
    viewSalesPriceHistory: 'Ver Historial de Precio de Venta',
    history: 'Historial',
    noPriceHistoryFound: 'No se encontró historial de precios. Agregue un nuevo precio para comenzar.',
    priceAddedSuccessfully: '¡Precio agregado exitosamente!',
    priceUpdatedSuccessfully: '¡Precio actualizado exitosamente!',
    priceDeletedSuccessfully: '¡Precio eliminado exitosamente!',
    deletePriceConfirm: '¿Eliminar este precio?',
    priceSyncSuccess: '¡Estado de precios sincronizado exitosamente!',
    errorSyncingPrices: 'Error al sincronizar precios',
    errorSavingPrice: 'Error al guardar precio',
    errorDeletingPrice: 'Error al eliminar precio',
    enterSalesPriceAndDate: 'Por favor ingrese precio de venta y fecha efectiva',
    update: 'Actualizar',
    
    // Traducciones específicas de Compras
    purchaseDetails: 'Detalles de Compra',
    productDetails: 'Detalles de Producto',
    invoiceSuppliers: 'Facturas de Proveedores',
    createNewPurchase: 'Crear Nueva Compra',
    selectProduct: 'Seleccionar producto...',
    unitCostWithAI: 'Costo Unitario con FI',
    addProduct: 'Agregar Producto',
    done: 'Listo',
    otherInvoicesAssociated: 'Otras Facturas Asociadas con esta Compra',
    supplierRncShort: 'RNC del Proveedor',
    taxAmountBase: 'Monto Base de Impuesto',
    purchaseOf: 'Compra de',
    selectType: 'Seleccionar tipo',
    addInvoice: 'Agregar Factura',
    noProductsFound: 'No se encontraron productos',
    noAssociatedInvoicesFound: 'No se encontraron facturas asociadas',
    productsAdded: 'Productos Agregados',
    items: 'artículos',
    associatedInvoicesCount: 'Facturas Asociadas',
    invoices: 'facturas',
    productTotal: 'Total de Productos',
    associatedCosts: 'Costos Asociados',
    grandTotal: 'TOTAL GENERAL',
    creating: 'Creando...',
    createPurchase: 'Crear Compra',
    goodsForInternalUse: 'Bienes para uso interno (PPE)',
    investmentsOrCapitalGoods: 'Inversiones o bienes de capital',
    servicesOrOther: 'Servicios u otros',
    policiesAndGuarantee: 'Pólizas y garantías',
    deposit: 'Depósito',
    includesProportionalShare: 'Incluye parte proporcional de costos asociados',
    adjustedUnitCostWithAssociatedCosts: 'Costo unitario ajustado con costos asociados',
    editable: 'Editable',
    editableTaxAmount: 'Monto de impuesto editable',
    
    // Compras
    newPurchase: 'Nueva Compra',
    registrationNumber: 'Número de Registro',
    registrationDate: 'Fecha de Registro',
    date: 'Fecha',
    supplier: 'Proveedor',
    supplierRnc: 'RNC del Proveedor',
    supplierName: 'Nombre del Proveedor',
    selectSupplier: 'Seleccionar un proveedor',
    ncf: 'NCF',
    purchaseType: 'Tipo de Compra',
    paymentTerms: 'Términos de Pago',
    paymentMethod: 'Método de Pago',
    paymentStatus: 'Estado de Pago',
    cash: 'Efectivo',
    cheque: 'Cheque',
    credit: 'Crédito',
    bankTransfer: 'Transferencia Bancaria',
    creditCard: 'Tarjeta de Crédito',
    unpaid: 'No Pagado',
    partial: 'Parcial',
    paidAmount: 'Monto Pagado',
    balanceDue: 'Saldo Pendiente',
    
    // Facturas Asociadas
    associatedInvoices: 'Otras Facturas Asociadas con esta Compra',
    concept: 'Concepto',
    freight: 'Flete',
    customs: 'Aduanas',
    insurance: 'Seguro',
    handling: 'Manejo',
    storage: 'Almacenamiento',
    other: 'Otro',
    
    // Ventas
    newSale: 'Nueva Venta',
    client: 'Cliente',
    clientRnc: 'RNC del Cliente',
    clientName: 'Nombre del Cliente',
    selectClient: 'Seleccionar un cliente',
    saleType: 'Tipo de Venta',
    discount: 'Descuento',
    newClient: 'Nuevo Cliente',
    editClient: 'Editar Cliente',
    idTaxNumber: 'ID/Número Fiscal',
    rncsupplier: 'ID Fiscal',
    
    // Proveedores
    newSupplier: 'Nuevo Proveedor',
    editSupplier: 'Editar Proveedor',
    
    // Formularios
    required: 'Requerido',
    optional: 'Opcional',
    enterValue: 'Ingresar valor',
    selectOption: 'Seleccionar opción',
    
    // Encabezados de Tabla
    actions: 'Acciones',
    viewDetails: 'Ver Detalles',
    makePayment: 'Realizar Pago',
    collectPayment: 'Cobrar Pago',
    
    // Mensajes
    successCreate: 'Creado exitosamente',
    successUpdate: 'Actualizado exitosamente',
    successDelete: 'Eliminado exitosamente',
    errorCreate: 'Error al crear',
    errorUpdate: 'Error al actualizar',
    errorDelete: 'Error al eliminar',
    confirmDelete: '¿Está seguro de que desea eliminar este elemento?',
    noData: 'No hay datos disponibles',
    loading: 'Cargando...',
    
    // Resumen de Compra
    purchaseSummary: 'Resumen de Compra',
    createSale: 'Crear Venta',
    
    // Varios
    show: 'Mostrar',
    hide: 'Ocultar',
    merchandiseForSale: 'Mercancía para venta o consumo',
    service: 'Servicio',
    fixedAsset: 'Activo Fijo',
    completed: 'Completado',
    pending: 'Pendiente',
    cancelled: 'Cancelado',
    saleNumber: 'Número de Venta',
    purchaseNumber: 'Número de Compra',
    totalAmount: 'Monto Total',
    paymentAmount: 'Monto de Pago',
    paymentType: 'Tipo de Pago',
    addProducts: 'Agregar Productos',
    product: 'Producto',
    
    // Alertas y Mensajes de Pago
    noOutstandingInvoicesSupplier: '⚠️ No se encontraron facturas pendientes para este proveedor.\n\nPosibles razones:\n1. Todas las compras están pagadas\n2. Las compras son de tipo Efectivo (no Crédito)\n3. No existen compras para este proveedor',
    noOutstandingInvoicesClient: '⚠️ No se encontraron facturas pendientes para este cliente.\n\nPosibles razones:\n1. Todas las ventas están pagadas\n2. Las ventas son de tipo Efectivo (no Crédito)\n3. No existen ventas para este cliente',
    errorLoadingInvoices: 'Error al cargar facturas pendientes. Revise la consola para más detalles.',
    pleaseSelectEntity: 'Por favor seleccione un proveedor o cliente',
    warningNoInvoices: '⚠️ ADVERTENCIA: ¡No se seleccionaron facturas!\n\nEste pago se registrará pero NO se aplicará a ninguna factura.\nLos saldos de compra/venta NO se actualizarán.\n\n¿Desea continuar de todos modos?\n\nHaga clic en "Cancelar" para volver y seleccionar facturas.',
    paymentSavedSuccess: '✅ ¡Pago guardado exitosamente!\n\nAplicado a {count} factura(s).',
    paymentSavedNoInvoices: '⚠️ Pago guardado pero NO aplicado a ninguna factura.\n\nPuede eliminarlo y recrearlo con selección de facturas.',
    selectSupplierOrClient: 'Seleccionar Proveedor/Cliente',
    invoicesToApplyPayment: 'Facturas a las que se aplicará este pago',
    checkToSelect: 'Marcar para seleccionar factura',
    totalToApply: 'Monto Total a Aplicar',
    overpaymentDetected: 'Sobrepago Detectado',
    overpaymentMessage: 'El monto del pago ({payment}) excede el monto total aplicado ({applied}). El exceso de {excess} se registrará como saldo a crédito para uso futuro.',
    enterValidAmount: 'Por favor ingrese un monto de pago válido',
    
    // Cuentas por Pagar y Cobrar
    accountsPayable: 'Cuentas por Pagar',
    accountsReceivable: 'Cuentas por Cobrar',
    moneyYouOwe: 'Dinero que debes (a compañías de tarjetas de crédito, proveedores a crédito, etc.)',
    moneyOwedToYou: 'Dinero que te deben (de ventas con tarjeta de crédito, créditos de clientes, etc.)',
    received: 'Recibido',
    balanceYouOwe: 'Saldo (Debes)',
    allStatus: 'Todos los Estados',
    supplierCodeAndName: 'Código y Nombre del Proveedor',
    purchaseDate: 'Fecha de Compra',
    paymentDeadline: 'Fecha Límite de Pago',
    type: 'Tipo',
    relatedDocumentNumber: 'Número de Documento Relacionado',
    balance: 'Saldo',
    action: 'Acción',
    paid: 'Pagado',
    pay: 'Pagar',
    unit: 'Unidad',
    qty: 'Cant',
    noAccountsPayableFound: 'No se encontraron cuentas por pagar',
    noAccountsReceivableFound: 'No se encontraron cuentas por cobrar',
    recordPayment: 'Registrar Pago',
    document: 'Documento',
    alreadyPaid: 'Ya Pagado',
    enterAmount: 'Ingresar monto',
    confirmPayment: 'Confirmar Pago',
    collect: 'Cobrar',
    clickToEditDeadline: 'Clic para editar fecha límite',
    invalidDate: 'Fecha inválida',
    pleaseSelectValidDeadline: 'Por favor seleccione una fecha límite válida',
    deadlineUpdated: 'Fecha límite actualizada',
    paymentDeadlineHasBeenUpdated: 'La fecha límite de pago ha sido actualizada',
    
    // Caja
    dailyCashManagement: 'Gestión y seguimiento diario de efectivo',
    newTransaction: 'Nueva Transacción',
    totalInflow: 'Total de Entradas',
    totalOutflow: 'Total de Salidas',
    areYouSureDeleteTransaction: '¿Está seguro de que desea eliminar esta transacción?',
    errorSavingTransaction: 'Error al guardar transacción',
    errorDeletingTransaction: 'Error al eliminar transacción',
    noTransactionsFound: 'No se encontraron transacciones',
    
    // Reportes
    businessReports: 'Reportes de Negocio',
    analyticsAndInsights: 'Análisis e información para su negocio',
    to: 'a',
    salesOverview: 'Resumen de Ventas',
    purchasesOverview: 'Resumen de Compras',
    cashFlowOverview: 'Resumen de Flujo de Caja',
    inventoryOverview: 'Resumen de Inventario',
    lowStockProducts: 'Productos con Stock Bajo',
    totalInventoryValue: 'Valor Total del Inventario',
    profitAnalysis: 'Análisis de Ganancias',
    grossProfit: 'Ganancia Bruta',
    quickActions: 'Acciones Rápidas',
    viewInventorySheet: 'Ver Hoja de Inventario',
    viewDetailedInventory: 'Ver inventario detallado',
    viewPaymentsReport: 'Ver Reporte de Pagos',
    viewDetailedPayments: 'Ver pagos detallados',
    exportReports: 'Exportar Reportes',
    downloadPDF: 'Descargar PDF',
    totalRevenue: 'Ingresos Totales',
    
    // Caja específico
    bankDeposit: 'Depósito Bancario',
    endOfDayReport: 'Reporte de Fin de Día',
    recordCashCheckDeposit: 'Registrar depósito de efectivo/cheque al banco',
    cashRegisterName: 'Nombre de Caja',
    bankAccountName: 'Nombre de Cuenta Bancaria',
    bankName: 'Nombre del Banco',
    recordDeposit: 'Registrar Depósito',
    collectionSummary: 'Resumen de Cobros',
    cashCollections: 'Cobros en Efectivo',
    checkCollections: 'Cobros en Cheque',
    bankTransfers: 'Transferencias Bancarias',
    bankDeposits: 'Depósitos Bancarios',
    creditCardCollections: 'Cobros con Tarjeta de Crédito',
    totalCollections: 'TOTAL DE COBROS',
    mainCashRegister: 'Caja Principal',
    businessCheckingAccount: 'Cuenta Corriente Empresarial',
    dailyCashDeposit: 'Depósito diario de efectivo',
    transactionType: 'Tipo de Transacción',
    relatedDocType: 'Tipo de Documento Relacionado',
    documentNumber: 'Número de Documento',
    clientRncCedula: 'RNC/Cédula del Cliente',
    newCashTransaction: 'Nueva Transacción de Caja',
    registrationHash: 'Registro #',
    source: 'Fuente',
    docNumber: 'Doc #',
    bankAccount: 'Cuenta Bancaria',
    originalType: 'Tipo Original',
    method: 'Método',
    allTransactions: 'Todas las Transacciones',
    inflowMoneyIn: 'Entrada (Dinero Entrante)',
    outflowMoneyOut: 'Salida (Dinero Saliente)',
    searchTransactions: 'Buscar transacciones...',
    inflow: 'Entrada',
    outflow: 'Salida',
    debitCard: 'Tarjeta de Débito',
    check: 'Cheque',
    
    // Registro Bancario específico
    bankRegister: 'Registro Bancario',
    currentBankBalance: 'Saldo Bancario Actual',
    newBankTransaction: 'Nueva Transacción Bancaria',
    bankAccountTransactions: 'Seguimiento de transacciones bancarias (transferencias y depósitos)',
    accountNumber: 'Número de Cuenta',
    referenceNumber: 'Número de Referencia',
    describeTransaction: 'Describa la transacción...',
    createTransaction: 'Crear Transacción',
    cashInflows: 'Efectivo Recibido (Ventas, etc.)',
    cashOutflows: 'Efectivo Pagado (Compras, Gastos)',
    expectedCashInRegister: 'Efectivo Esperado en Caja',
    openingBalance: 'Saldo Inicial',
    closingBalance: 'Saldo Final',
    cashIn: 'Efectivo Entrante',
    depositIn: 'Depósito Entrante',
    bankTransferIn: 'Transferencia Bancaria Entrante',
    cashOut: 'Efectivo Saliente',
    depositOut: 'Depósito Saliente',
    bankTransferOut: 'Transferencia Bancaria Saliente',
    totalIn: 'Total Entrante',
    totalOut: 'Total Saliente',
    partyEntity: 'Parte/Entidad',
    clientSupplierBank: 'Cliente/Proveedor/Banco',
    cost: 'Costo',
    costOfGoodsSold: 'Costo de Bienes Vendidos',
    
    // Fase 1 - Datos Maestros
    bankAccounts: 'Cuentas Bancarias',
    newBankAccount: 'Nueva Cuenta Bancaria',
    editBankAccount: 'Editar Cuenta Bancaria',
    accountType: 'Tipo de Cuenta',
    checking: 'Corriente',
    savings: 'Ahorros',
    location: 'Ubicación',
    cashRegisters: 'Cajas Registradoras',
    newCashRegister: 'Nueva Caja Registradora',
    editCashRegister: 'Editar Caja Registradora',
    cards: 'Tarjetas',
    newCard: 'Nueva Tarjeta',
    editCard: 'Editar Tarjeta',
    cardNumber: 'Número de Tarjeta',
    last4Digits: 'Últimos 4 Dígitos',
    cardType: 'Tipo de Tarjeta',
    cardBrand: 'Marca de Tarjeta',
    cardName: 'Nombre de Tarjeta',
    financers: 'Financiadores',
    financersDesc: 'Gestionar inversores y fuentes de financiamiento',
    newFinancer: 'Nuevo Financiador',
    editFinancer: 'Editar Financiador',
    contactPerson: 'Persona de Contacto',
    email: 'Correo Electrónico',
    financerType: 'Tipo de Financiador',
    bank: 'Banco',
    investor: 'Inversionista',
    rnc: 'RNC',
    create: 'Crear',
    
    // Fase 3 - Actualizaciones de Caja
    selectCashRegister: 'Seleccionar Caja',
    selectBankAccount: 'Seleccionar Cuenta Bancaria',
    selectCustomer: 'Seleccionar Cliente',
    selectFinancer: 'Seleccionar Financiador',
    selectContributor: 'Seleccionar Contribuyente',
    selectLender: 'Seleccionar Prestamista',
    selectInvoices: 'Seleccionar Facturas',
    arCollection: 'Cobro de CxC',
    contribution: 'Aporte',
    loan: 'Préstamo',
    correction: 'Corrección',
    chequeNumber: 'Número de Cheque',
    receiptNumber: 'Número de Recibo',
    bankCheque: 'Cheque Bancario',
    pendingInvoices: 'Facturas Pendientes',
    transactionCreated: '¡Transacción creada exitosamente!',
    corrections: 'Correcciones',
    sale: 'Venta',
    netCashPosition: 'Posición Neta de Efectivo',
    
    // Fase 4 - Actualizaciones de Registro Bancario
    chequeTransferNumber: 'Cheque/Transferencia #',
    selectInvoicesToPay: 'Seleccionar Facturas a Pagar',
    selectedInvoicesTotal: 'Total de Facturas Seleccionadas',
    noPendingInvoicesForSupplier: 'No se encontraron facturas pendientes para este proveedor',
    
    // Traducciones faltantes de Registro Bancario
    fromAccountsPayable: 'De Cuentas por Pagar',
    creditPurchasePayment: 'Pago de Compra a Crédito',
    thisTransactionWillPay: 'Esta transacción pagará la deuda de compra a crédito. El formulario ha sido prellenado con los detalles del pago.',
    pleaseKeepTransactionType: 'Por favor mantenga el Tipo de Transacción como "SALIDA" para el pago.',
    pleaseSelectAtLeastOneInvoice: 'Por favor seleccione al menos una factura para pagar',
    deleteTransactionConfirm: '¿Está seguro de que desea eliminar esta transacción?',
    selectSpecificInvoices: 'Seleccione las facturas/compras específicas que desea pagar. Cada elemento muestra información detallada de la factura.',
    invoice: 'factura',
    invoicesLowercase: 'facturas',
    paymentColon: 'Pago:',
    all: 'Todos',
    // Traducciones faltantes de Cuentas por Pagar
    payableTo: 'Pagadero A',
    cardCompany: 'Compañía de Tarjeta',
    loadingAccountsPayable: 'Cargando cuentas por pagar',
    pleaseSelectCardForPayment: 'Por favor seleccione una tarjeta para el pago',
    paymentRecordedSuccessfully: 'Pago registrado exitosamente',
    recordingPayment: 'Registrando pago',
    updatingDeadline: 'Actualizando fecha límite',
    paymentForCreditPurchase: 'Pago por Compra a Crédito',
    creditPurchasePaymentType: 'Pago de Compra a Crédito',
    payViaBankButton: 'Pagar vía Banco',
    
    // Traducciones faltantes de Cuentas por Pagar
    selectDebitCard: 'Seleccionar Tarjeta de Débito',
    immediatePayment: 'Pago Inmediato',
    selectADebitCard: 'Seleccionar una tarjeta de débito...',
    debitCardExplanation: 'Tarjeta de DÉBITO: Dinero deducido del banco inmediatamente para pagar esta deuda',
    creditCardPayment: 'Pago con Tarjeta de Crédito',
    cardLabel: 'Tarjeta:',
    whatHappens: 'Qué sucede:',
    creditLimitRestored: 'El límite de crédito será restaurado por',
    noCardSelectionNeeded: 'No se necesita selección de tarjeta - el sistema usará automáticamente la tarjeta de crédito original.',
    confirmPaymentRestoreCredit: 'Confirmar Pago y Restaurar Crédito',
    
    // Traducciones adicionales faltantes
    saleDetails: 'Detalles de Venta',
    processCardPayment: 'Procesar Pago con Tarjeta',
    editProduct: 'Editar Producto',
    deleteProduct: 'Eliminar Producto',
    editNetwork: 'Editar Red',
    deleteNetwork: 'Eliminar Red',
    viewDepreciationSchedule: 'Ver Cronograma de Depreciación',
    ncfNumber: 'Número NCF',
    unitCostPlaceholder: 'Costo Unitario',
    allTypes: 'Todos los Tipos',
    debitNote: 'Nota de Débito',
    creditNote: 'Nota de Crédito',
    adjustment: 'Ajuste',
    debitNoteND: 'Nota de Débito (ND)',
    creditNoteNC: 'Nota de Crédito (NC)',
    adjustmentAJ: 'Ajuste (AJ)',
    creditSaleCollection: 'Cobro de Venta a Crédito',

    // ✅ Navegación de Módulos y Barra Lateral
    backToDashboard: 'Volver al Panel',
    favorites: 'Favoritos',
    hidden: 'Ocultos',
    resetToDefault: 'Restablecer por Defecto',
    customizeMenu: 'Personalizar menú',
    doneCustomizing: 'Listo',
    openMenu: 'Abrir menú',
    closeMenu: 'Cerrar menú',
    addToFavorites: 'Agregar a favoritos',
    removeFromFavorites: 'Quitar de favoritos',
    resetMenuConfirm: '¿Restablecer el menú al diseño predeterminado?',
    noItemsAvailable: 'No hay elementos disponibles',

    // ✅ Nombres de Módulos
    masterData: 'Datos Maestros',
    masterDataDesc: 'Configure sus datos de negocio',
    masterDataTitle: 'Gestión de Datos Maestros',
    masterDataSubtitle: 'Configure y gestione sus datos de negocio principales. Seleccione una opción de la barra lateral para comenzar.',

    transactionsModule: 'Transacciones',
    transactionsDesc: 'Gestionar operaciones diarias',
    transactionsTitle: 'Gestión de Transacciones',
    transactionsSubtitle: 'Registre y gestione todas sus transacciones comerciales. Seleccione una opción de la barra lateral para comenzar.',

    expensesModule: 'Gastos',
    expensesDesc: 'Rastrear y gestionar gastos',
    expensesTitle: 'Gestión de Gastos',
    expensesSubtitle: 'Rastree y gestione todos sus gastos comerciales. Seleccione una opción de la barra lateral para comenzar.',

    accountingModule: 'Contabilidad',
    accountingDesc: 'Gestión financiera y reportes',
    accountingTitle: 'Gestión Contable y Financiera',
    accountingSubtitle: 'Gestione sus registros financieros y genere reportes. Seleccione una opción de la barra lateral para comenzar.',

    assetsModule: 'Activos y Financiamiento',
    assetsDesc: 'Gestionar activos e inversiones',
    assetsTitle: 'Gestión de Activos y Financiamiento',
    assetsSubtitle: 'Gestione activos fijos, inversiones, financiamiento y genere reportes. Seleccione una opción de la barra lateral para comenzar.',

    administrationModule: 'Administración',
    administrationDesc: 'Gestión del sistema y seguridad',
    administrationTitle: 'Administración del Sistema',
    administrationSubtitleAdmin: 'Gestione usuarios, roles, permisos y configuración del sistema. Seleccione una opción de la barra lateral para comenzar.',
    administrationSubtitleUser: 'Gestione la clasificación de datos y solicitudes de eliminación de transacciones. Seleccione una opción de la barra lateral para comenzar.',

    reportsModule: 'Reportes',
    reportsDesc: 'Inteligencia de negocios y análisis',
    reportsTitle: 'Reportes y Análisis',
    reportsSubtitle: 'Genere reportes de inteligencia de negocios y análisis. Seleccione una opción de la barra lateral para comenzar.',

    // ✅ Panel de Módulos
    welcomeTitle: 'Bienvenido a su Sistema ERP',
    welcomeSubtitle: 'Seleccione un módulo para comenzar con sus operaciones comerciales',
    welcomeCustomizing: 'Arrastre módulos para reordenar • Haga clic en el ícono de ojo para ocultar',
    customizeDashboard: 'Personalizar Panel',
    doneCustomizingDashboard: 'Listo',
    hiddenModules: 'Módulos Ocultos',
    resetDashboardConfirm: '¿Restablecer el panel al diseño predeterminado?',

    // ✅ Autenticación
    auth_loginTitle: 'Bienvenido de Nuevo',
    auth_loginSubtitle: 'Inicie sesión en su cuenta ERP',
    auth_registerTitle: 'Cree su Cuenta',
    auth_registerSubtitle: 'Únase a nuestro sistema ERP',
    auth_noAccount: '¿No tiene una cuenta?',
    auth_haveAccount: '¿Ya tiene una cuenta?',

    // ✅ Mensajes de Validación
    validation_fillAllFields: 'Por favor complete todos los campos',
    validation_fillRequired: 'Por favor complete todos los campos requeridos',
    validation_selectSupplier: 'Por favor seleccione un proveedor',
    validation_selectCard: 'Por favor seleccione una tarjeta',
    validation_validAmount: 'Por favor ingrese un monto de pago válido',
    validation_validAmountGreaterZero: 'Por favor ingrese un monto válido mayor que cero',
    validation_amountExceedsSale: 'El monto del pago no puede exceder el monto de la venta',
    validation_amountExceedsUsed: 'La cantidad no puede exceder el crédito utilizado de $',
    validation_selectBankAccount: 'Por favor seleccione una cuenta bancaria',
    validation_selectBankForMethod: 'Por favor seleccione una cuenta bancaria para este método de pago',
    validation_selectCardPayment: 'Por favor seleccione una tarjeta de crédito para pagar',
    validation_selectCategory: 'Por favor seleccione una categoría de gasto',
    validation_selectType: 'Por favor seleccione un tipo de gasto',
    validation_amountGreaterThanZero: 'El monto del pago debe ser mayor que 0',
    validation_fillChequeDetails: 'Por favor complete el número de cheque y la fecha',
    validation_fillTransferDetails: 'Por favor complete el número de transferencia y la fecha',
    validation_fillCardDetails: 'Por favor complete todos los detalles de pago con tarjeta',
    validation_enterCheckNumber: 'Por favor ingrese un número de cheque',
    validation_selectBankAccountRestore: 'Por favor seleccione una cuenta bancaria',

    // ✅ Etiquetas
    labels_emailAddress: 'Dirección de Correo Electrónico',
    labels_password: 'Contraseña',
    labels_rememberMe: 'Recuérdame',
    labels_firstName: 'Nombre',
    labels_lastName: 'Apellido',
    labels_role: 'Rol',
    labels_saleDetails: 'Detalles de Venta',
    labels_saleNumber: 'Número de Venta:',
    labels_amountDue: 'Monto Adeudado:',
    labels_cardType: 'Tipo:',
    labels_bank: 'Banco:',
    labels_creditLimit: 'Límite de Crédito:',
    labels_availableLimit: 'Disponible:',
    labels_creditCardAutoSelected: 'Tarjeta de Crédito (Seleccionada Automáticamente)',
    labels_selectCreditCard: 'Seleccione la Tarjeta de Crédito para Pagar',
    labels_customer: 'Cliente:',
    labels_paymentAmount: 'Monto de Pago:',
    labels_paymentMethod: 'Método de Pago:',
    labels_invoices: 'Facturas:',
    labels_cashRegister: 'Caja:',
    labels_bankAccount: 'Cuenta Bancaria:',
    labels_error: 'Error',
    labels_availableCredit: 'Crédito Disponible:',
    labels_creditWillBeUsed: 'Crédito que Se Utilizará:',
    labels_invoiceBalance: 'Saldo de Factura:',
    labels_cashPaymentNeeded: 'Pago en Efectivo Necesario:',
    labels_selectedMethod: 'Método de Pago Seleccionado:',
    labels_creditOnly: 'Pago Solo con Crédito',
    labels_paymentNotAllowed: 'Pago No Permitido',
    labels_maximum: 'Máximo: $',
    labels_currentUsedCredit: '(crédito actual utilizado)',
    labels_supplier: 'Proveedor',
    labels_usedCredit: 'Crédito Utilizado',
    labels_selectDebitCard: 'Seleccionar Tarjeta de Débito',
    labels_card: 'Tarjeta',
    labels_available: 'Disponible: ₹',
    labels_required: 'Requerido: ₹',
    labels_approvalRoleLimit: 'Rol de Aprobación y Límite',

    // ✅ Enlaces
    links_forgotPassword: '¿Olvidó su contraseña?',
    links_termsOfService: 'Términos de Servicio',

    // ✅ Botones
    buttons_signIn: 'Iniciar Sesión',
    buttons_signUp: 'Registrarse',
    buttons_cancel: 'Cancelar',
    buttons_processPayment: 'Procesar Pago',
    buttons_processCreditPayment: 'Procesar Pago de Crédito',
    buttons_restoreCredit: 'Restaurar Crédito',
    buttons_logout: 'Cerrar Sesión',
    buttons_edit: 'Editar',
    buttons_delete: 'Eliminar',
    buttons_firstPage: 'Primera Página',
    buttons_previousPage: 'Página Anterior',
    buttons_nextPage: 'Página Siguiente',
    buttons_lastPage: 'Última Página',
    buttons_removeFromFavorites: 'Quitar de favoritos',
    buttons_addToFavorites: 'Agregar a favoritos',
    buttons_hideMenuItem: 'Ocultar este elemento del menú',
    buttons_createAccount: 'Crear Cuenta',

    // ✅ Estados/Cargando
    states_signingIn: 'Iniciando sesión...',
    states_creatingAccount: 'Creando cuenta...',
    states_calculating: 'Calculando estrategia de pago óptima...',
    states_processing: 'Procesando...',
    states_restoring: 'Restaurando...',
    states_loading: 'Cargando...',

    // ✅ Mensajes
    messages_featureComingSoon: '¡La funcionalidad de contraseña olvidada vendrá pronto!',
    messages_creditOnlyExplanation: 'Este pago se procesará completamente utilizando el saldo de crédito existente del cliente. No se requiere selección de método de pago ni caja.',
    messages_paymentSuccess: 'Pago procesado exitosamente',
    messages_cardPaymentSuccess: '¡Pago con tarjeta procesado exitosamente!',
    messages_creditOnlyPaymentSuccess: 'Pago procesado exitosamente utilizando saldo de crédito',

    // ✅ Errores
    errors_loadCards: 'Error al cargar las tarjetas disponibles',
    errors_processPayment: 'Error al procesar el pago',
    errors_failedProcessCardPayment: 'Error al procesar el pago con tarjeta',
    errors_restoreCard: 'Error al restaurar la tarjeta de crédito. Por favor intente de nuevo.',
    errors_insufficientBalance: 'Saldo insuficiente en',
    errors_insufficientCreditLimit: 'Límite de crédito insuficiente en',
    errors_createExpense: 'Error al crear gasto',

    // ✅ Marcadores de Posición
    placeholders_enterEmail: 'Ingrese su correo electrónico',
    placeholders_enterPassword: 'Ingrese su contraseña',
    placeholders_exampleFirstName: 'Juan',
    placeholders_exampleLastName: 'Pérez',
    placeholders_exampleEmail: 'juan.perez@ejemplo.com',
    placeholders_confirmPassword: 'Confirme su contraseña',
    placeholders_selectCard: 'Elija una tarjeta...',
    placeholders_amount: '0.00',
    placeholders_paymentDescription: 'Descripción del pago...',
    placeholders_enterAmount: 'Ingrese monto de pago',
    placeholders_checkReference: 'Número de cheque, ID de transferencia o referencia',
    placeholders_paymentNotes: 'Notas adicionales sobre este pago',
    placeholders_expenseDescription: 'Breve descripción del gasto...',
    placeholders_checkNumber: 'Ingrese número de cheque',
    placeholders_transferReference: 'Ingrese referencia de transferencia',
    placeholders_transactionReference: 'ID de transacción o referencia',
    placeholders_selectPaymentType: 'Seleccione tipo de pago...',
    placeholders_selectSupplier: 'Seleccione proveedor...',
    placeholders_selectClient: 'Seleccione cliente...',
    placeholders_selectBankAccount: 'Seleccione cuenta bancaria...',
    placeholders_searchTypes: 'Buscar tipos de gastos...',
    placeholders_searchCategories: 'Buscar categorías...',
    placeholders_referenceNumber: 'Número de referencia opcional',
    placeholders_notes: 'Notas opcionales sobre esta restauración',
    placeholders_voucherNumber: 'Ingrese número de comprobante/autorización',

    // ✅ Opciones/Menús Desplegables
    options_selectCard: 'Elija una tarjeta...',
    options_selectAll: 'Todos',
    options_credit: 'Crédito (Pagar Después)',
    options_cash: 'Efectivo',
    options_bankTransfer: 'Transferencia Bancaria',
    options_cheque: 'Cheque',
    options_check: 'Cheque',
    options_debitCard: 'Tarjeta de Débito (Inmediato)',
    options_creditCard: 'Tarjeta de Crédito (Crea Pasivo)',
    options_servicesOther: 'Servicios u Otros',
    options_prepaidExpenses: 'Gastos Prepagados',
    options_policiesGuarantee: 'Pólizas y Garantías',

    // ✅ Grupos de Opciones
    optgroups_bankPayments: 'Pagos Bancarios (Inmediato)',
    optgroups_cardPayments: 'Pagos con Tarjeta',

    // ✅ Secciones/Encabezados
    sections_creditAnalysis: 'Análisis de Saldo de Crédito del Cliente',
    sections_paymentBreakdown: 'Desglose de Pagos',
    sections_registerConfig: 'Configuración de Pago de Caja',

    // ✅ Elementos de Pago
    payments_fromCredit: 'Desde Saldo de Crédito del Cliente',
    payments_cashRequired: 'Pago en Efectivo Requerido',
    payments_newCredit: 'Nuevo Saldo de Crédito',

    // ✅ Títulos Modales
    modals_cardPaymentTitle: 'Procesar Pago con Tarjeta',
    modals_creditPaymentTitle: 'Pago Inteligente del Cliente con Saldo de Crédito',
    modals_restoreCardTitle: 'Restaurar Tarjeta de Crédito',

    // ✅ Accesibilidad
    aria_selectExpenseType: 'Seleccionar tipo de gasto',
    aria_selectExpenseCategory: 'Seleccionar categoría de gasto',

    // ✅ Sugerencias/Consejos
    hints_dragReorder: 'Arrastra para reordenar',

    // ✅ Paginación
    pagination_ellipsis: '...',

    // 🆕 Mensajes Toast
    pleaseAddAtLeastOneProduct: 'Por favor agregue al menos un producto para la compra de mercancías',
    enterSupplierRncNameTax: 'Por favor ingrese RNC del Proveedor, Nombre del Proveedor y Monto de Impuesto',
    selectPaymentTypeInvoice: 'Por favor seleccione un tipo de pago para la factura',
    selectCardForPaymentType: 'Por favor seleccione una tarjeta para el tipo de pago seleccionado',
    selectBankAccountForPaymentType: 'Por favor seleccione una cuenta bancaria para el tipo de pago seleccionado',
    selectProductValidQuantityCost: 'Por favor seleccione un producto e ingrese cantidad y costo unitario válidos',
    paymentDeletedSuccess: 'Pago eliminado exitosamente',
    investmentMarkedPaidSuccess: 'Inversión marcada como pagada exitosamente',
    failedMarkInvestmentPaid: 'Error al marcar inversión como pagada',
    paymentUpdatedSuccess: 'Pago actualizado exitosamente',
    failedUpdatePayment: 'Error al actualizar pago',
    failedFixInvestmentStatus: 'Error al corregir estado de inversión',
    investmentAgreementCreatedSuccess: 'Acuerdo de inversión creado exitosamente',
    failedCleanupAccountsPayable: 'Error al limpiar entradas de Cuentas por Pagar',
    financerUpdatedSuccess: 'Financiador actualizado exitosamente',
    financerCreatedSuccess: 'Financiador creado exitosamente',
    financerDeletedSuccess: 'Financiador eliminado exitosamente',
    categoryNameRequired: 'El nombre de la categoría es requerido',
    categoryCodeRequired: 'El código de la categoría es requerido',
    categoryUpdatedSuccess: 'Categoría actualizada exitosamente',
    categoryCreatedSuccess: 'Categoría creada exitosamente',
    typeNameRequired: 'El nombre del tipo es requerido',
    typeCodeRequired: 'El código del tipo es requerido',
    expenseTypeAddedSuccess: 'Tipo de gasto agregado exitosamente',
    categoryDeletedSuccess: 'Categoría eliminada exitosamente',
    cashRegisterUpdatedSuccess: 'Caja registradora actualizada exitosamente',
    cashRegisterCreatedSuccess: 'Caja registradora creada exitosamente',
    cashRegisterDeletedSuccess: 'Caja registradora eliminada exitosamente',
    failedLoadDashboardData: 'Error al cargar datos del panel',
    failedLoadExpiringData: 'Error al cargar datos de vencimiento',
    failedLoadClassifications: 'Error al cargar clasificaciones',
    complianceReportDownloadedSuccess: 'Reporte de cumplimiento descargado exitosamente',
    failedDownloadReport: 'Error al descargar reporte',
    selectPaymentMethod: 'Por favor seleccione un método de pago',
    selectCashRegisterForCash: 'Por favor seleccione una caja registradora para pagos en efectivo',
    selectBankAccountForBank: 'Por favor seleccione una cuenta bancaria para pagos bancarios',
    selectInvestmentLoanAgreement: 'Por favor seleccione un acuerdo de inversión/préstamo',
    selectDebitCardNetwork: 'Por favor seleccione una red de pago con tarjeta de débito',
    excelExportFunctionality: 'La funcionalidad de exportación a Excel se implementará aquí',
    pleaseSelectSupplier: 'Por favor seleccione un proveedor',
    fillChequeNumberDate: 'Por favor complete el número de cheque y la fecha',
    fillTransferNumberDate: 'Por favor complete el número de transferencia y la fecha',
    fillAllCardPaymentDetails: 'Por favor complete todos los detalles del pago con tarjeta',
    forgotPasswordComingSoon: '¡La funcionalidad de recuperación de contraseña estará disponible pronto!',
    paymentCompletedSuccessfully: '¡Pago completado exitosamente! El estado de Cuentas por Pagar ha sido actualizado.',
    transactionCreatedSuccessfully: '¡Transacción creada exitosamente!',
    smartPaymentCompletedSuccess: '¡Pago inteligente completado exitosamente! Los saldos de crédito se aplicaron automáticamente.',
    smartPaymentCompleted: '¡Pago inteligente completado exitosamente!',
    areYouSureDeleteSupplier: '¿Está seguro de que desea eliminar este proveedor?',
    createDefaultChartOfAccounts: 'Esto creará el Plan de Cuentas predeterminado. ¿Continuar?',
    resetDashboardToDefault: '¿Restablecer el panel al diseño predeterminado?',

    // 🆕 Etiquetas de Formulario
    paymentReferenceRequired: 'Referencia de Pago *',
    enterPaymentReferenceVoucher: 'Ingrese referencia de pago/número de comprobante',
    voucherDateRequired: 'Fecha de Comprobante *',
    chequeNumberRequired: 'Número de Cheque *',
    enterChequeNumber: 'Ingrese número de cheque',
    chequeDateRequired: 'Fecha de Cheque *',
    transferNumberRequired: 'Número de Transferencia *',
    enterTransferReferenceNumber: 'Ingrese número de referencia de transferencia',
    transferDateRequired: 'Fecha de Transferencia *',
    searchSuppliers: 'Buscar proveedores...',
    loadingSuppliers: 'Cargando proveedores...',

    // 🆕 UI Común
    loadingData: 'Cargando datos...',
    loadingPage: 'Cargando página...',
    view: 'Ver',
    download: 'Descargar',
    upload: 'Subir',
    refresh: 'Actualizar',
    reset: 'Restablecer',
    apply: 'Aplicar',
    clear: 'Limpiar',
    from: 'Desde',
    dateRange: 'Rango de Fechas',
    selectDate: 'Seleccionar Fecha',
    selectAll: 'Seleccionar Todo',
    deselectAll: 'Deseleccionar Todo',
    showing: 'Mostrando',
    of: 'de',
    entries: 'entradas',
    page: 'Página',
    rowsPerPage: 'Filas por página',
    areYouSure: '¿Está seguro?',
    thisActionCannotBeUndone: 'Esta acción no se puede deshacer',
    confirmAction: 'Confirmar Acción',
    success: 'Éxito',
    warning: 'Advertencia',
    info: 'Información',

    // 🆕 Gestión de Roles de Usuario
    userRoleManagement: 'Gestión de Roles de Usuario',
    loadingUserRoles: 'Cargando roles de usuario...',
    syncAllAdminManagerRoles: 'Sincronizar Todos los Roles Admin/Manager',
    assignRole: 'Asignar Rol',
    totalUsers: 'Total de Usuarios',
    emailHeader: 'Correo Electrónico',
    fullNameHeader: 'Nombre Completo',
    basicRoleHeader: 'Rol Básico',
    approvalRoleHeader: 'Rol de Aprobación',
    approvalLimitHeader: 'Límite de Aprobación',
    canDelegateHeader: 'Puede Delegar',
    assignedAtHeader: 'Asignado En',
    actionsHeader: 'Acciones',
    notSyncedYet: 'Aún no sincronizado',
    yesLabel: 'Sí',
    noLabel: 'No',
    editApprovalLimit: 'Editar Límite de Aprobación',
    removeRole: 'Eliminar Rol',
    assignRoleToUser: 'Asignar Rol a Usuario',
    userEmailRequired: 'Correo Electrónico del Usuario *',
    searchByEmailOrName: 'Buscar por correo o nombre...',
    roleRequired: 'Rol *',
    selectARole: 'Seleccione un rol...',
    customApprovalLimit: 'Límite de Aprobación Personalizado (Opcional)',
    leaveEmptyForDefault: 'Dejar vacío para usar límite predeterminado',
    canDelegateApproval: 'Puede delegar aprobación a otros',
    assigning: 'Asignando...',
    assignRoleButton: 'Asignar Rol',
    updateApprovalLimit: 'Actualizar Límite de Aprobación',
    userLabel: 'Usuario',
    currentLimit: 'Límite Actual',
    newApprovalLimitRequired: 'Nuevo Límite de Aprobación *',
    enterNewLimit: 'Ingrese nuevo límite de aprobación',
    reasonForChangeRequired: 'Razón del Cambio *',
    explainWhyChanging: 'Explique por qué está cambiando este límite...',
    updating: 'Actualizando...',
    updateLimitButton: 'Actualizar Límite',
    roleAssignedSuccess: '¡Rol asignado exitosamente!',
    approvalLimitUpdatedSuccess: '¡Límite de aprobación actualizado exitosamente!',
    enterReasonForRemoving: 'Ingrese razón para eliminar rol de',
    roleRemovedSuccess: '¡Rol eliminado exitosamente!',
    syncConfirmation: 'Esto sincronizará todos los usuarios admin y manager con sus roles de aprobación. ¿Continuar?',
    syncCompletedSuccess: '¡Sincronización completada exitosamente!',
    syncedLabel: 'Sincronizados',
    skippedLabel: 'Omitidos',
    errorsLabel: 'Errores',

    // 🆕 Activos Fijos
    newFixedAsset: 'Nuevo Activo Fijo',
    managePropertyPlantEquipment: 'Gestionar propiedad, planta y equipo',

    // 🆕 Ajustes
    newAdjustment: 'Nuevo Ajuste',
    editAdjustment: 'Editar Ajuste',
    adjustmentAmountMustBeGreaterThanZero: 'El monto del ajuste debe ser mayor que 0. Agregue productos o ingrese un monto.',

    // 🆕 Páginas Adicionales
    newExpense: 'Nuevo Gasto',
    newPrepaidExpense: 'Nuevo Gasto Prepagado',
    newInvestment: 'Nueva Inversión',
    
    // Gastos Empresariales
    businessExpenses: 'Gastos Empresariales',
    
    // Gastos Prepagados
    prepaidExpensesDesc: 'Rastrear pagos anticipados y amortización automática',
    totalPrepaid: 'Total Prepagado',
    totalAmortized: 'Total Amortizado',
    remainingBalance: 'Saldo Restante',
    openingBalanceEntries: 'Entradas de Saldo Inicial',
    configuration: 'Configuración',
    
    // Inversiones
    investmentsDesc: 'Rastrear inversiones, bonos y bienes de capital',
    totalAcquisitionCost: 'Costo Total de Adquisición',
    currentValue: 'Valor Actual',
    totalInvestment: 'Inversión Total',
    
    // Acuerdos de Inversión
    investmentAgreementsDesc: 'Gestionar acuerdos de inversión y préstamos antes de recibir dinero',
    totalAgreements: 'Total de Acuerdos',
    totalCommitted: 'Total Comprometido',
    newAgreement: 'Nuevo Acuerdo',
    
    // Inversionistas
    investorsDesc: 'Gestionar y rastrear todas las inversiones de inversionistas',
    totalInvestors: 'Total de Inversionistas',
    totalInvested: 'Total Invertido',
    
    // Reporte de Inversiones
    investmentReportDesc: 'Rendimiento de Cartera y Análisis de ROI',
    
    // Libro Mayor
    generalLedgerDesc: 'Historial completo de transacciones',
    
    // Saldo Inicial
    openingBalanceDesc: 'Establecer saldos iniciales de cuentas para su sistema contable',
    addEntry: 'Agregar Entrada',
    
    // Marcadores de Posición
    placeholders_searchExpenses: 'Buscar gastos...',
    placeholders_searchPrepaid: 'Buscar por código, nombre, tipo...',
    placeholders_searchInvestments: 'Buscar inversiones...',
    
    // Botones
    buttons_refresh: 'Actualizar',
  }
};

type Language = 'en' | 'es';
type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Get saved language from localStorage or default to English
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'es') ? saved : 'en';
  });

  // Save language preference to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  // Translation function
  const t = (key: TranslationKey): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
