import React, { createContext, useContext, useState, useEffect } from 'react';

// Translation objects
const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    products: 'Products',
    inventory: 'Inventory',
    purchases: 'Purchases',
    sales: 'Sales',
    clients: 'Clients',
    suppliers: 'Suppliers',
    fixedAssets: 'Fixed Assets',
    investments: 'Investments',
    prepaidExpenses: 'Prepaid Expenses',
    payments: 'Payments',
    cashRegister: 'Cash Register',
    adjustments: 'Adjustments',
    reports: 'Reports',
    
    // Common Actions
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    print: 'Print',
    close: 'Close',
    submit: 'Submit',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    
    // Common Fields
    code: 'Code',
    name: 'Name',
    phone: 'Phone',
    address: 'Address',
    notes: 'Notes',
    
    // Dashboard
    totalSales: 'Total Sales',
    totalClients: 'Total Clients',
    totalPurchases: 'Total Purchases',
    netRevenue: 'Net Revenue',
    profit: 'Profit',
    loss: 'Loss',
    lowStockAlert: 'Low Stock Alert',
    recentSales: 'Recent Sales',
    recentPurchases: 'Recent Purchases',
    unpaidSales: 'Unpaid Sales',
    unpaidPurchases: 'Unpaid Purchases',
    totalProducts: 'Total Products',
    activeProducts: 'Active Products',
    loadingDashboard: 'Loading dashboard...',
    noSalesYet: 'No sales yet',
    noPurchasesYet: 'No purchases yet',
    
    // Inventory
    inventorySheet: 'Inventory Sheet',
    trackPurchasesAndSales: 'Track purchases and sales of goods',
    exportToExcel: 'Export to Excel',
    startDate: 'Start Date',
    endDate: 'End Date',
    productFilter: 'Product Filter',
    allProducts: 'All Products',
    searchProduct: 'Search Product',
    registrationNo: 'Registration No.',
    rncSupplier: 'RNC Supplier',
    operation: 'Operation',
    amountInAmount: 'Amount in Amount',
    balanceInAmount: 'Balance in Amount',
    balanceIn: 'Balance in',
    balanceInQuantity: 'Balance in Quantity',
    averageUnitCost: 'Average Unit Cost',
    year: 'Year',
    month: 'Month',
    currentBalance: 'Current Balance',
    averageCost: 'Average Cost',
    totalIncome: 'Total Income',
    totalCost: 'Total Cost',
    grossMargin: 'Gross Margin',
    grossMarginPercent: '% Gross Margin',
    grossMarginOnRevenue: '% Gross Margin on Revenue',
    grossMarginOnCost: '% Gross Margin on Cost',
    noInventoryMovements: 'No inventory movements found for the selected criteria',
    adjustDateRange: 'Try adjusting your date range or product filter',
    
    // Payments
    paymentsManagement: 'Payments Management',
    trackPayments: 'Track payments to suppliers and from clients',
    newPayment: 'New Payment',
    editPayment: 'Edit Payment',
    paymentsOut: 'Payments Out',
    paymentsIn: 'Payments In',
    netCashFlow: 'Net Cash Flow',
    allPaymentTypes: 'All Payment Types',
    paymentOut: 'Payment Out',
    paymentIn: 'Payment In',
    toSuppliers: 'To Suppliers',
    fromClients: 'From Clients',
    paymentOutToSupplier: 'Payment Out (To Supplier)',
    paymentInFromClient: 'Payment In (From Client)',
    invoicesToApply: 'Invoices to which this payment will be applied',
    listOutstandingCredit: 'List outstanding credit invoices',
    listOutstandingCash: 'List outstanding cash invoices',
    invoiceNo: 'Invoice No.',
    balancePending: 'Balance Pending',
    amountToPay: 'Amount to Pay',
    totalAmountToApply: 'Total Amount to Apply',
    
    // Products
    newProduct: 'New Product',
    productCode: 'Product Code',
    productName: 'Product Name',
    description: 'Description',
    unitOfMeasurement: 'Unit of Measurement',
    amount: 'Amount',
    quantity: 'Quantity',
    unitPrice: 'Unit Cost',
    unitCost: 'Unit Cost',
    subtotal: 'Subtotal',
    tax: 'Tax',
    taxRate: 'Tax Rate',
    taxAmount: 'Tax Amount',
    total: 'Total',
    stock: 'Stock',
    category: 'Category',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    price: 'Price',
    salesPrice: 'Sales Price',
    salesPriceHistory: 'Sales Price History',
    priceHistory: 'Price History',
    addNewPrice: 'Add New Price',
    editPrice: 'Edit Price',
    effectiveDate: 'Effective Date',
    syncStatus: 'Sync Status',
    viewSalesPriceHistory: 'View Sales Price History',
    history: 'History',
    noPriceHistoryFound: 'No price history found. Add a new price to get started.',
    priceAddedSuccessfully: 'Price added successfully!',
    priceUpdatedSuccessfully: 'Price updated successfully!',
    priceDeletedSuccessfully: 'Price deleted successfully!',
    deletePriceConfirm: 'Delete this price?',
    priceSyncSuccess: 'Price status synchronized successfully!',
    errorSyncingPrices: 'Error syncing prices',
    errorSavingPrice: 'Error saving price',
    errorDeletingPrice: 'Error deleting price',
    enterSalesPriceAndDate: 'Please enter sales price and effective date',
    update: 'Update',
    
    // Purchase-specific translations
    purchaseDetails: 'Purchase Details',
    productDetails: 'Product Details',
    invoiceSuppliers: 'Invoice Suppliers',
    createNewPurchase: 'Create New Purchase',
    selectProduct: 'Select product...',
    unitCostWithAI: 'Unit Cost with AI',
    addProduct: 'Add Product',
    done: 'Done',
    otherInvoicesAssociated: 'Other Invoices Associated with this Purchase',
    supplierRncShort: "Supplier's RNC",
    taxAmountBase: 'Tax Amount (Base)',
    purchaseOf: 'Purchase of',
    selectType: 'Select type',
    addInvoice: 'Add Invoice',
    noProductsFound: 'No products found',
    noAssociatedInvoicesFound: 'No associated invoices found',
    productsAdded: 'Products Added',
    items: 'items',
    associatedInvoicesCount: 'Associated Invoices',
    invoices: 'invoices',
    productTotal: 'Product Total',
    associatedCosts: 'Associated Costs',
    grandTotal: 'GRAND TOTAL',
    creating: 'Creating...',
    createPurchase: 'Create Purchase',
    goodsForInternalUse: 'Goods for internal use (PPE)',
    investmentsOrCapitalGoods: 'Investments or capital goods',
    servicesOrOther: 'Services or other',
    policiesAndGuarantee: 'Policies and guarantee',
    deposit: 'Deposit',
    includesProportionalShare: 'Includes proportional share of associated costs',
    adjustedUnitCostWithAssociatedCosts: 'Adjusted unit cost with associated costs',
    editable: 'Editable',
    editableTaxAmount: 'Editable tax amount',
    
    // Purchases
    newPurchase: 'New Purchase',
    registrationNumber: 'Registration Number',
    registrationDate: 'Registration Date',
    date: 'Date',
    supplier: 'Supplier',
    supplierRnc: "Supplier's RNC",
    supplierName: 'Supplier Name',
    selectSupplier: 'Select a supplier',
    ncf: 'NCF',
    purchaseType: 'Purchase Type',
    paymentTerms: 'Payment Terms',
    paymentMethod: 'Payment Method',
    paymentStatus: 'Payment Status',
    cash: 'Cash',
    cheque: 'Cheque',
    credit: 'Credit',
    bankTransfer: 'Bank Transfer',
    creditCard: 'Credit Card',
    unpaid: 'Unpaid',
    partial: 'Partial',
    paidAmount: 'Paid Amount',
    balanceDue: 'Balance Due',
    
    // Associated Invoices
    associatedInvoices: 'Other Invoices Associated with this Purchase',
    concept: 'Concept',
    freight: 'Freight',
    customs: 'Customs',
    insurance: 'Insurance',
    handling: 'Handling',
    storage: 'Storage',
    other: 'Other',
    
    // Sales
    newSale: 'New Sale',
    client: 'Client',
    clientRnc: "Client's RNC",
    clientName: 'Client Name',
    selectClient: 'Select a client',
    saleType: 'Sale Type',
    discount: 'Discount',
    newClient: 'New Client',
    editClient: 'Edit Client',
    idTaxNumber: 'ID/Tax Number',
    rncsupplier: 'RNC Supplier',
    
    // Suppliers
    newSupplier: 'New Supplier',
    editSupplier: 'Edit Supplier',
    
    // Forms
    required: 'Required',
    optional: 'Optional',
    enterValue: 'Enter value',
    selectOption: 'Select option',
    
    // Table Headers
    actions: 'Actions',
    viewDetails: 'View Details',
    makePayment: 'Make Payment',
    collectPayment: 'Collect Payment',
    
    // Messages
    successCreate: 'Created successfully',
    successUpdate: 'Updated successfully',
    successDelete: 'Deleted successfully',
    errorCreate: 'Error creating',
    errorUpdate: 'Error updating',
    errorDelete: 'Error deleting',
    confirmDelete: 'Are you sure you want to delete this item?',
    noData: 'No data available',
    loading: 'Loading...',
    
    // Purchase Summary
    purchaseSummary: 'Purchase Summary',
    createSale: 'Create Sale',
    
    // Misc
    show: 'Show',
    hide: 'Hide',
    merchandiseForSale: 'Merchandise for sale or consumption',
    service: 'Service',
    fixedAsset: 'Fixed Asset',
    completed: 'Completed',
    pending: 'Pending',
    cancelled: 'Cancelled',
    saleNumber: 'Sale Number',
    purchaseNumber: 'Purchase Number',
    totalAmount: 'Total Amount',
    paymentAmount: 'Payment Amount',
    paymentType: 'Payment Type',
    addProducts: 'Add Products',
    product: 'Product',
    
    // Payment Alerts and Messages
    noOutstandingInvoicesSupplier: '⚠️ No outstanding invoices found for this supplier.\n\nPossible reasons:\n1. All purchases are paid\n2. Purchases are Cash type (not Credit)\n3. No purchases exist for this supplier',
    noOutstandingInvoicesClient: '⚠️ No outstanding invoices found for this client.\n\nPossible reasons:\n1. All sales are paid\n2. Sales are Cash type (not Credit)\n3. No sales exist for this client',
    errorLoadingInvoices: 'Error loading outstanding invoices. Check console for details.',
    pleaseSelectEntity: 'Please select a supplier or client',
    warningNoInvoices: '⚠️ WARNING: No invoices selected!\n\nThis payment will be recorded but NOT applied to any invoices.\nThe purchase/sale balances will NOT be updated.\n\nDo you want to continue anyway?\n\nClick "Cancel" to go back and select invoices.',
    paymentSavedSuccess: '✅ Payment saved successfully!\n\nApplied to {count} invoice(s).',
    paymentSavedNoInvoices: '⚠️ Payment saved but NOT applied to any invoices.\n\nYou can delete and recreate it with invoice selection.',
    selectSupplierOrClient: 'Select Supplier/Client',
    invoicesToApplyPayment: 'Invoices to which this payment will be applied',
    checkToSelect: 'Check to select invoice',
    totalToApply: 'Total Amount to Apply',
    overpaymentDetected: 'Overpayment Detected',
    overpaymentMessage: 'Payment amount ({payment}) exceeds total applied amount ({applied}). The excess amount of {excess} will be recorded as a credit balance for future use.',
    enterValidAmount: 'Please enter a valid payment amount',
    
    // Accounts Payable & Receivable
    accountsPayable: 'Accounts Payable',
    accountsReceivable: 'Accounts Receivable',
    moneyYouOwe: 'Money you owe (to credit card companies, suppliers on credit, etc.)',
    moneyOwedToYou: 'Money owed to you (from credit card sales, client credits, etc.)',
    received: 'Received',
    balanceYouOwe: 'Balance (You Owe)',
    allStatus: 'All Status',
    supplierCodeAndName: 'Supplier Code and Name',
    purchaseDate: 'Purchase Date',
    paymentDeadline: 'Payment Deadline',
    type: 'Type',
    relatedDocumentNumber: 'Related Document Number',
    balance: 'Balance',
    action: 'Action',
    paid: 'Paid',
    pay: 'Pay',
    unit: 'Unit',
    qty: 'Qty',
    noAccountsPayableFound: 'No accounts payable found',
    noAccountsReceivableFound: 'No accounts receivable found',
    recordPayment: 'Record Payment',
    document: 'Document',
    alreadyPaid: 'Already Paid',
    enterAmount: 'Enter amount',
    confirmPayment: 'Confirm Payment',
    collect: 'Collect',
    clickToEditDeadline: 'Click to edit deadline',
    invalidDate: 'Invalid date',
    pleaseSelectValidDeadline: 'Please select a valid deadline',
    deadlineUpdated: 'Deadline updated',
    paymentDeadlineHasBeenUpdated: 'Payment deadline has been updated',
    
    // Cash Register
    dailyCashManagement: 'Daily cash management and tracking',
    newTransaction: 'New Transaction',
    totalInflow: 'Total Inflow',
    totalOutflow: 'Total Outflow',
    areYouSureDeleteTransaction: 'Are you sure you want to delete this transaction?',
    errorSavingTransaction: 'Error saving transaction',
    errorDeletingTransaction: 'Error deleting transaction',
    noTransactionsFound: 'No transactions found',
    
    // Reports
    businessReports: 'Business Reports',
    analyticsAndInsights: 'Analytics and insights for your business',
    to: 'to',
    salesOverview: 'Sales Overview',
    purchasesOverview: 'Purchases Overview',
    cashFlowOverview: 'Cash Flow Overview',
    inventoryOverview: 'Inventory Overview',
    lowStockProducts: 'Low Stock Products',
    totalInventoryValue: 'Total Inventory Value',
    profitAnalysis: 'Profit Analysis',
    grossProfit: 'Gross Profit',
    quickActions: 'Quick Actions',
    viewInventorySheet: 'View Inventory Sheet',
    viewDetailedInventory: 'View Detailed Inventory',
    viewPaymentsReport: 'View Payments Report',
    viewDetailedPayments: 'View Detailed Payments',
    exportReports: 'Export Reports',
    downloadPDF: 'Download PDF',
    totalRevenue: 'Total Revenue',
    
    // Cash Register specific
    bankDeposit: 'Bank Deposit',
    endOfDayReport: 'End of Day Report',
    recordCashCheckDeposit: 'Record cash/check deposit to bank account',
    cashRegisterName: 'Cash Register Name',
    bankAccountName: 'Bank Account Name',
    bankName: 'Bank Name',
    recordDeposit: 'Record Deposit',
    collectionSummary: 'Collections Summary',
    cashCollections: 'Cash Collections',
    checkCollections: 'Check Collections',
    bankTransfers: 'Bank Transfers',
    bankDeposits: 'Bank Deposits',
    creditCardCollections: 'Credit Card Collections',
    totalCollections: 'TOTAL COLLECTIONS',
    mainCashRegister: 'Main Cash Register',
    businessCheckingAccount: 'Business Checking Account',
    dailyCashDeposit: 'Daily cash deposit',
    transactionType: 'Transaction Type',
    relatedDocType: 'Related Document Type',
    documentNumber: 'Document Number',
    clientRncCedula: 'Client RNC/Cedula',
    newCashTransaction: 'New Cash Transaction',
    registrationHash: 'Registration #',
    source: 'Source',
    docNumber: 'Doc #',
    bankAccount: 'Bank Account',
    originalType: 'Original Type',
    method: 'Method',
    allTransactions: 'All Transactions',
    inflowMoneyIn: 'Inflow (Money In)',
    outflowMoneyOut: 'Outflow (Money Out)',
    searchTransactions: 'Search transactions...',
    inflow: 'Inflow',
    outflow: 'Outflow',
    debitCard: 'Debit Card',
    check: 'Check',
    
    // Bank Register specific
    bankRegister: 'Bank Register',
    currentBankBalance: 'Current Bank Balance',
    newBankTransaction: 'New Bank Transaction',
    bankAccountTransactions: 'Track bank account transactions (transfers and deposits)',
    accountNumber: 'Account Number',
    referenceNumber: 'Reference Number',
    describeTransaction: 'Describe the transaction...',
    createTransaction: 'Create Transaction',
    cashInflows: 'Cash Received (Sales, etc.)',
    cashOutflows: 'Cash Paid Out (Purchases, Expenses)',
    expectedCashInRegister: 'Expected Cash in Register',
    openingBalance: 'Opening Balance',
    closingBalance: 'Closing Balance',
    cashIn: 'Cash In',
    depositIn: 'Deposit In',
    bankTransferIn: 'Bank Transfer In',
    cashOut: 'Cash Out',
    depositOut: 'Deposit Out',
    bankTransferOut: 'Bank Transfer Out',
    totalIn: 'Total In',
    totalOut: 'Total Out',
    partyEntity: 'Party/Entity',
    clientSupplierBank: 'Client/Supplier/Bank',
    cost: 'Cost',
    costOfGoodsSold: 'Cost of Goods Sold',
    
    // Phase 1 - Master Data
    bankAccounts: 'Bank Accounts',
    newBankAccount: 'New Bank Account',
    editBankAccount: 'Edit Bank Account',
    accountType: 'Account Type',
    checking: 'Current',
    savings: 'Savings',
    location: 'Location',
    cashRegisters: 'Cash Registers',
    newCashRegister: 'New Cash Register',
    editCashRegister: 'Edit Cash Register',
    cards: 'Cards',
    newCard: 'New Card',
    editCard: 'Edit Card',
    cardNumber: 'Card Number',
    last4Digits: 'Last 4 Digits',
    cardType: 'Card Type',
    cardBrand: 'Card Brand',
    cardName: 'Card Name',
    financers: 'Financers',
    newFinancer: 'New Financer',
    editFinancer: 'Edit Financer',
    contactPerson: 'Contact Person',
    email: 'Email',
    financerType: 'Financer Type',
    bank: 'Bank',
    investor: 'Investor',
    rnc: 'RNC',
    create: 'Create',
    
    // Phase 3 - Cash Register Updates
    selectCashRegister: 'Select Cash Register',
    selectBankAccount: 'Select Bank Account',
    selectCustomer: 'Select Customer',
    selectFinancer: 'Select Financer',
    selectContributor: 'Select Contributor',
    selectLender: 'Select Lender',
    selectInvoices: 'Select Invoices',
    arCollection: 'AR Collection',
    contribution: 'Contribution',
    loan: 'Loan',
    correction: 'Correction',
    chequeNumber: 'Cheque Number',
    receiptNumber: 'Receipt Number',
    bankCheque: 'Bank Cheque',
    pendingInvoices: 'Pending Invoices',
    transactionCreated: 'Transaction created successfully!',
    corrections: 'Corrections',
    sale: 'Sale',
    netCashPosition: 'Net Cash Position',
    
    // Phase 4 - Bank Register Updates
    chequeTransferNumber: 'Cheque/Transfer #',
    selectInvoicesToPay: 'Select Invoices to Pay',
    selectedInvoicesTotal: 'Selected Invoices Total',
    noPendingInvoicesForSupplier: 'No pending invoices found for this supplier',
    
    // Missing Bank Register translations
    fromAccountsPayable: 'From Accounts Payable',
    creditPurchasePayment: 'Credit Purchase Payment',
    thisTransactionWillPay: 'This transaction will pay the credit purchase debt. The form has been pre-filled with the payment details.',
    pleaseKeepTransactionType: 'Please keep Transaction Type as "OUTFLOW" for payment.',
    pleaseSelectAtLeastOneInvoice: 'Please select at least one invoice to pay',
    deleteTransactionConfirm: 'Are you sure you want to delete this transaction?',
    selectSpecificInvoices: 'Select the specific invoices/purchases you want to pay. Each item shows detailed invoice information.',
    invoice: 'invoice',
    invoicesLowercase: 'invoices',
    paymentColon: 'Payment:',
    all: 'All',
    // Missing AccountsPayable translations
    payableTo: 'Payable To',
    cardCompany: 'Card Company',
    loadingAccountsPayable: 'Loading accounts payable',
    pleaseSelectCardForPayment: 'Please select a card for payment',
    paymentRecordedSuccessfully: 'Payment recorded successfully',
    recordingPayment: 'Recording payment',
    updatingDeadline: 'Updating deadline',
    paymentForCreditPurchase: 'Payment for Credit Purchase',
    creditPurchasePaymentType: 'Credit Purchase Payment',
    payViaBankButton: 'Pay via Bank',
    
    // Missing AccountsPayable translations
    selectDebitCard: 'Select Debit Card',
    immediatePayment: 'Immediate Payment',
    selectADebitCard: 'Select a debit card...',
    debitCardExplanation: 'DEBIT card: Money deducted from bank immediately to pay this debt',
    creditCardPayment: 'Credit Card Payment',
    cardLabel: 'Card:',
    whatHappens: 'What happens:',
    creditLimitRestored: 'Credit limit will be restored by',
    noCardSelectionNeeded: 'No card selection needed - the system will automatically use the original credit card.',
    confirmPaymentRestoreCredit: 'Confirm Payment & Restore Credit',
    
    // Additional missing translations
    saleDetails: 'Sale Details',
    processCardPayment: 'Process Card Payment',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    editNetwork: 'Edit Network',
    deleteNetwork: 'Delete Network',
    viewDepreciationSchedule: 'View Depreciation Schedule',
    ncfNumber: 'NCF Number',
    unitCostPlaceholder: 'Unit Cost',
    allTypes: 'All Types',
    debitNote: 'Debit Note',
    creditNote: 'Credit Note',
    adjustment: 'Adjustment',
    debitNoteND: 'Debit Note (ND)',
    creditNoteNC: 'Credit Note (NC)',
    adjustmentAJ: 'Adjustment (AJ)',
    creditSaleCollection: 'Credit Sale Collection',
  },
  
  es: {
    // Navegación
    dashboard: 'Panel',
    products: 'Productos',
    inventory: 'Inventario',
    purchases: 'Compras',
    sales: 'Ventas',
    clients: 'Clientes',
    suppliers: 'Proveedores',
    fixedAssets: 'Activos Fijos',
    investments: 'Inversiones',
    prepaidExpenses: 'Gastos Prepagados',
    payments: 'Pagos',
    cashRegister: 'Caja',
    adjustments: 'Ajustes',
    reports: 'Reportes',
    
    // Acciones Comunes
    add: 'Agregar',
    edit: 'Editar',
    delete: 'Eliminar',
    save: 'Guardar',
    cancel: 'Cancelar',
    search: 'Buscar',
    filter: 'Filtrar',
    export: 'Exportar',
    import: 'Importar',
    print: 'Imprimir',
    close: 'Cerrar',
    submit: 'Enviar',
    confirm: 'Confirmar',
    back: 'Atrás',
    next: 'Siguiente',
    
    // Campos Comunes
    code: 'Código',
    name: 'Nombre',
    phone: 'Teléfono',
    address: 'Dirección',
    notes: 'Notas',
    
    // Panel
    totalSales: 'Total de Ventas',
    totalClients: 'Total de Clientes',
    totalPurchases: 'Total de Compras',
    netRevenue: 'Ingresos Netos',
    profit: 'Ganancia',
    loss: 'Pérdida',
    lowStockAlert: 'Alerta de Stock Bajo',
    recentSales: 'Ventas Recientes',
    recentPurchases: 'Compras Recientes',
    unpaidSales: 'Ventas No Pagadas',
    unpaidPurchases: 'Compras No Pagadas',
    totalProducts: 'Total de Productos',
    activeProducts: 'Productos Activos',
    loadingDashboard: 'Cargando panel...',
    noSalesYet: 'Aún no hay ventas',
    noPurchasesYet: 'Aún no hay compras',
    
    // Inventario
    inventorySheet: 'Hoja de Inventario',
    trackPurchasesAndSales: 'Seguimiento de compras y ventas de mercancías',
    exportToExcel: 'Exportar a Excel',
    startDate: 'Fecha de Inicio',
    endDate: 'Fecha de Fin',
    productFilter: 'Filtro de Producto',
    allProducts: 'Todos los Productos',
    searchProduct: 'Buscar Producto',
    registrationNo: 'Número de Registro',
    rncSupplier: 'RNC Proveedor',
    operation: 'Operación',
    amountInAmount: 'Cantidad en Monto',
    balanceInAmount: 'Saldo en Monto',
    balanceIn: 'Saldo en',
    balanceInQuantity: 'Saldo en Cantidad',
    averageUnitCost: 'Costo Unitario Promedio',
    year: 'Año',
    month: 'Mes',
    currentBalance: 'Saldo Actual',
    averageCost: 'Costo Promedio',
    totalIncome: 'Ingresos Totales',
    totalCost: 'Costo Total',
    grossMargin: 'Margen Bruto',
    grossMarginPercent: '% Margen Bruto',
    grossMarginOnRevenue: '% Margen Bruto sobre Ingresos',
    grossMarginOnCost: '% Margen Bruto sobre Costo',
    noInventoryMovements: 'No se encontraron movimientos de inventario para los criterios seleccionados',
    adjustDateRange: 'Intente ajustar su rango de fechas o filtro de producto',
    
    // Pagos
    paymentsManagement: 'Gestión de Pagos',
    trackPayments: 'Seguimiento de pagos a proveedores y de clientes',
    newPayment: 'Nuevo Pago',
    editPayment: 'Editar Pago',
    paymentsOut: 'Pagos Salientes',
    paymentsIn: 'Pagos Entrantes',
    netCashFlow: 'Flujo de Caja Neto',
    allPaymentTypes: 'Todos los Tipos de Pago',
    paymentOut: 'Pago Saliente',
    paymentIn: 'Pago Entrante',
    toSuppliers: 'A Proveedores',
    fromClients: 'De Clientes',
    paymentOutToSupplier: 'Pago Saliente (A Proveedor)',
    paymentInFromClient: 'Pago Entrante (De Cliente)',
    invoicesToApply: 'Facturas a las que se aplicará este pago',
    listOutstandingCredit: 'Listar facturas de crédito pendientes',
    listOutstandingCash: 'Listar facturas de efectivo pendientes',
    invoiceNo: 'Número de Factura',
    balancePending: 'Saldo Pendiente',
    amountToPay: 'Monto a Pagar',
    totalAmountToApply: 'Monto Total a Aplicar',
    
    // Productos
    newProduct: 'Nuevo Producto',
    productCode: 'Código de Producto',
    productName: 'Nombre del Producto',
    description: 'Descripción',
    unitOfMeasurement: 'Unidad de Medida',
    amount: 'Cantidad',
    quantity: 'Cantidad',
    unitPrice: 'Costo Unitario',
    unitCost: 'Costo Unitario',
    subtotal: 'Subtotal',
    tax: 'Impuesto',
    taxRate: 'Tasa de Impuesto',
    taxAmount: 'Monto de Impuesto',
    total: 'Total',
    stock: 'Existencia',
    category: 'Categoría',
    status: 'Estado',
    active: 'Activo',
    inactive: 'Inactivo',
    price: 'Precio',
    salesPrice: 'Precio de Venta',
    salesPriceHistory: 'Historial de Precio de Venta',
    priceHistory: 'Historial de Precios',
    addNewPrice: 'Agregar Nuevo Precio',
    editPrice: 'Editar Precio',
    effectiveDate: 'Fecha Efectiva',
    syncStatus: 'Sincronizar Estado',
    viewSalesPriceHistory: 'Ver Historial de Precio de Venta',
    history: 'Historial',
    noPriceHistoryFound: 'No se encontró historial de precios. Agregue un nuevo precio para comenzar.',
    priceAddedSuccessfully: '¡Precio agregado exitosamente!',
    priceUpdatedSuccessfully: '¡Precio actualizado exitosamente!',
    priceDeletedSuccessfully: '¡Precio eliminado exitosamente!',
    deletePriceConfirm: '¿Eliminar este precio?',
    priceSyncSuccess: '¡Estado de precios sincronizado exitosamente!',
    errorSyncingPrices: 'Error al sincronizar precios',
    errorSavingPrice: 'Error al guardar precio',
    errorDeletingPrice: 'Error al eliminar precio',
    enterSalesPriceAndDate: 'Por favor ingrese precio de venta y fecha efectiva',
    update: 'Actualizar',
    
    // Traducciones específicas de Compras
    purchaseDetails: 'Detalles de Compra',
    productDetails: 'Detalles de Producto',
    invoiceSuppliers: 'Facturas de Proveedores',
    createNewPurchase: 'Crear Nueva Compra',
    selectProduct: 'Seleccionar producto...',
    unitCostWithAI: 'Costo Unitario con FI',
    addProduct: 'Agregar Producto',
    done: 'Listo',
    otherInvoicesAssociated: 'Otras Facturas Asociadas con esta Compra',
    supplierRncShort: 'RNC del Proveedor',
    taxAmountBase: 'Monto Base de Impuesto',
    purchaseOf: 'Compra de',
    selectType: 'Seleccionar tipo',
    addInvoice: 'Agregar Factura',
    noProductsFound: 'No se encontraron productos',
    noAssociatedInvoicesFound: 'No se encontraron facturas asociadas',
    productsAdded: 'Productos Agregados',
    items: 'artículos',
    associatedInvoicesCount: 'Facturas Asociadas',
    invoices: 'facturas',
    productTotal: 'Total de Productos',
    associatedCosts: 'Costos Asociados',
    grandTotal: 'TOTAL GENERAL',
    creating: 'Creando...',
    createPurchase: 'Crear Compra',
    goodsForInternalUse: 'Bienes para uso interno (PPE)',
    investmentsOrCapitalGoods: 'Inversiones o bienes de capital',
    servicesOrOther: 'Servicios u otros',
    policiesAndGuarantee: 'Pólizas y garantías',
    deposit: 'Depósito',
    includesProportionalShare: 'Incluye parte proporcional de costos asociados',
    adjustedUnitCostWithAssociatedCosts: 'Costo unitario ajustado con costos asociados',
    editable: 'Editable',
    editableTaxAmount: 'Monto de impuesto editable',
    
    // Compras
    newPurchase: 'Nueva Compra',
    registrationNumber: 'Número de Registro',
    registrationDate: 'Fecha de Registro',
    date: 'Fecha',
    supplier: 'Proveedor',
    supplierRnc: 'RNC del Proveedor',
    supplierName: 'Nombre del Proveedor',
    selectSupplier: 'Seleccionar un proveedor',
    ncf: 'NCF',
    purchaseType: 'Tipo de Compra',
    paymentTerms: 'Términos de Pago',
    paymentMethod: 'Método de Pago',
    paymentStatus: 'Estado de Pago',
    cash: 'Efectivo',
    cheque: 'Cheque',
    credit: 'Crédito',
    bankTransfer: 'Transferencia Bancaria',
    creditCard: 'Tarjeta de Crédito',
    unpaid: 'No Pagado',
    partial: 'Parcial',
    paidAmount: 'Monto Pagado',
    balanceDue: 'Saldo Pendiente',
    
    // Facturas Asociadas
    associatedInvoices: 'Otras Facturas Asociadas con esta Compra',
    concept: 'Concepto',
    freight: 'Flete',
    customs: 'Aduanas',
    insurance: 'Seguro',
    handling: 'Manejo',
    storage: 'Almacenamiento',
    other: 'Otro',
    
    // Ventas
    newSale: 'Nueva Venta',
    client: 'Cliente',
    clientRnc: 'RNC del Cliente',
    clientName: 'Nombre del Cliente',
    selectClient: 'Seleccionar un cliente',
    saleType: 'Tipo de Venta',
    discount: 'Descuento',
    newClient: 'Nuevo Cliente',
    editClient: 'Editar Cliente',
    idTaxNumber: 'ID/Número Fiscal',
    rncsupplier: 'ID Fiscal',
    
    // Proveedores
    newSupplier: 'Nuevo Proveedor',
    editSupplier: 'Editar Proveedor',
    
    // Formularios
    required: 'Requerido',
    optional: 'Opcional',
    enterValue: 'Ingresar valor',
    selectOption: 'Seleccionar opción',
    
    // Encabezados de Tabla
    actions: 'Acciones',
    viewDetails: 'Ver Detalles',
    makePayment: 'Realizar Pago',
    collectPayment: 'Cobrar Pago',
    
    // Mensajes
    successCreate: 'Creado exitosamente',
    successUpdate: 'Actualizado exitosamente',
    successDelete: 'Eliminado exitosamente',
    errorCreate: 'Error al crear',
    errorUpdate: 'Error al actualizar',
    errorDelete: 'Error al eliminar',
    confirmDelete: '¿Está seguro de que desea eliminar este elemento?',
    noData: 'No hay datos disponibles',
    loading: 'Cargando...',
    
    // Resumen de Compra
    purchaseSummary: 'Resumen de Compra',
    createSale: 'Crear Venta',
    
    // Varios
    show: 'Mostrar',
    hide: 'Ocultar',
    merchandiseForSale: 'Mercancía para venta o consumo',
    service: 'Servicio',
    fixedAsset: 'Activo Fijo',
    completed: 'Completado',
    pending: 'Pendiente',
    cancelled: 'Cancelado',
    saleNumber: 'Número de Venta',
    purchaseNumber: 'Número de Compra',
    totalAmount: 'Monto Total',
    paymentAmount: 'Monto de Pago',
    paymentType: 'Tipo de Pago',
    addProducts: 'Agregar Productos',
    product: 'Producto',
    
    // Alertas y Mensajes de Pago
    noOutstandingInvoicesSupplier: '⚠️ No se encontraron facturas pendientes para este proveedor.\n\nPosibles razones:\n1. Todas las compras están pagadas\n2. Las compras son de tipo Efectivo (no Crédito)\n3. No existen compras para este proveedor',
    noOutstandingInvoicesClient: '⚠️ No se encontraron facturas pendientes para este cliente.\n\nPosibles razones:\n1. Todas las ventas están pagadas\n2. Las ventas son de tipo Efectivo (no Crédito)\n3. No existen ventas para este cliente',
    errorLoadingInvoices: 'Error al cargar facturas pendientes. Revise la consola para más detalles.',
    pleaseSelectEntity: 'Por favor seleccione un proveedor o cliente',
    warningNoInvoices: '⚠️ ADVERTENCIA: ¡No se seleccionaron facturas!\n\nEste pago se registrará pero NO se aplicará a ninguna factura.\nLos saldos de compra/venta NO se actualizarán.\n\n¿Desea continuar de todos modos?\n\nHaga clic en "Cancelar" para volver y seleccionar facturas.',
    paymentSavedSuccess: '✅ ¡Pago guardado exitosamente!\n\nAplicado a {count} factura(s).',
    paymentSavedNoInvoices: '⚠️ Pago guardado pero NO aplicado a ninguna factura.\n\nPuede eliminarlo y recrearlo con selección de facturas.',
    selectSupplierOrClient: 'Seleccionar Proveedor/Cliente',
    invoicesToApplyPayment: 'Facturas a las que se aplicará este pago',
    checkToSelect: 'Marcar para seleccionar factura',
    totalToApply: 'Monto Total a Aplicar',
    overpaymentDetected: 'Sobrepago Detectado',
    overpaymentMessage: 'El monto del pago ({payment}) excede el monto total aplicado ({applied}). El exceso de {excess} se registrará como saldo a crédito para uso futuro.',
    enterValidAmount: 'Por favor ingrese un monto de pago válido',
    
    // Cuentas por Pagar y Cobrar
    accountsPayable: 'Cuentas por Pagar',
    accountsReceivable: 'Cuentas por Cobrar',
    moneyYouOwe: 'Dinero que debes (a compañías de tarjetas de crédito, proveedores a crédito, etc.)',
    moneyOwedToYou: 'Dinero que te deben (de ventas con tarjeta de crédito, créditos de clientes, etc.)',
    received: 'Recibido',
    balanceYouOwe: 'Saldo (Debes)',
    allStatus: 'Todos los Estados',
    supplierCodeAndName: 'Código y Nombre del Proveedor',
    purchaseDate: 'Fecha de Compra',
    paymentDeadline: 'Fecha Límite de Pago',
    type: 'Tipo',
    relatedDocumentNumber: 'Número de Documento Relacionado',
    balance: 'Saldo',
    action: 'Acción',
    paid: 'Pagado',
    pay: 'Pagar',
    unit: 'Unidad',
    qty: 'Cant',
    noAccountsPayableFound: 'No se encontraron cuentas por pagar',
    noAccountsReceivableFound: 'No se encontraron cuentas por cobrar',
    recordPayment: 'Registrar Pago',
    document: 'Documento',
    alreadyPaid: 'Ya Pagado',
    enterAmount: 'Ingresar monto',
    confirmPayment: 'Confirmar Pago',
    collect: 'Cobrar',
    clickToEditDeadline: 'Clic para editar fecha límite',
    invalidDate: 'Fecha inválida',
    pleaseSelectValidDeadline: 'Por favor seleccione una fecha límite válida',
    deadlineUpdated: 'Fecha límite actualizada',
    paymentDeadlineHasBeenUpdated: 'La fecha límite de pago ha sido actualizada',
    
    // Caja
    dailyCashManagement: 'Gestión y seguimiento diario de efectivo',
    newTransaction: 'Nueva Transacción',
    totalInflow: 'Total de Entradas',
    totalOutflow: 'Total de Salidas',
    areYouSureDeleteTransaction: '¿Está seguro de que desea eliminar esta transacción?',
    errorSavingTransaction: 'Error al guardar transacción',
    errorDeletingTransaction: 'Error al eliminar transacción',
    noTransactionsFound: 'No se encontraron transacciones',
    
    // Reportes
    businessReports: 'Reportes de Negocio',
    analyticsAndInsights: 'Análisis e información para su negocio',
    to: 'a',
    salesOverview: 'Resumen de Ventas',
    purchasesOverview: 'Resumen de Compras',
    cashFlowOverview: 'Resumen de Flujo de Caja',
    inventoryOverview: 'Resumen de Inventario',
    lowStockProducts: 'Productos con Stock Bajo',
    totalInventoryValue: 'Valor Total del Inventario',
    profitAnalysis: 'Análisis de Ganancias',
    grossProfit: 'Ganancia Bruta',
    quickActions: 'Acciones Rápidas',
    viewInventorySheet: 'Ver Hoja de Inventario',
    viewDetailedInventory: 'Ver inventario detallado',
    viewPaymentsReport: 'Ver Reporte de Pagos',
    viewDetailedPayments: 'Ver pagos detallados',
    exportReports: 'Exportar Reportes',
    downloadPDF: 'Descargar PDF',
    totalRevenue: 'Ingresos Totales',
    
    // Caja específico
    bankDeposit: 'Depósito Bancario',
    endOfDayReport: 'Reporte de Fin de Día',
    recordCashCheckDeposit: 'Registrar depósito de efectivo/cheque al banco',
    cashRegisterName: 'Nombre de Caja',
    bankAccountName: 'Nombre de Cuenta Bancaria',
    bankName: 'Nombre del Banco',
    recordDeposit: 'Registrar Depósito',
    collectionSummary: 'Resumen de Cobros',
    cashCollections: 'Cobros en Efectivo',
    checkCollections: 'Cobros en Cheque',
    bankTransfers: 'Transferencias Bancarias',
    bankDeposits: 'Depósitos Bancarios',
    creditCardCollections: 'Cobros con Tarjeta de Crédito',
    totalCollections: 'TOTAL DE COBROS',
    mainCashRegister: 'Caja Principal',
    businessCheckingAccount: 'Cuenta Corriente Empresarial',
    dailyCashDeposit: 'Depósito diario de efectivo',
    transactionType: 'Tipo de Transacción',
    relatedDocType: 'Tipo de Documento Relacionado',
    documentNumber: 'Número de Documento',
    clientRncCedula: 'RNC/Cédula del Cliente',
    newCashTransaction: 'Nueva Transacción de Caja',
    registrationHash: 'Registro #',
    source: 'Fuente',
    docNumber: 'Doc #',
    bankAccount: 'Cuenta Bancaria',
    originalType: 'Tipo Original',
    method: 'Método',
    allTransactions: 'Todas las Transacciones',
    inflowMoneyIn: 'Entrada (Dinero Entrante)',
    outflowMoneyOut: 'Salida (Dinero Saliente)',
    searchTransactions: 'Buscar transacciones...',
    inflow: 'Entrada',
    outflow: 'Salida',
    debitCard: 'Tarjeta de Débito',
    check: 'Cheque',
    
    // Registro Bancario específico
    bankRegister: 'Registro Bancario',
    currentBankBalance: 'Saldo Bancario Actual',
    newBankTransaction: 'Nueva Transacción Bancaria',
    bankAccountTransactions: 'Seguimiento de transacciones bancarias (transferencias y depósitos)',
    accountNumber: 'Número de Cuenta',
    referenceNumber: 'Número de Referencia',
    describeTransaction: 'Describa la transacción...',
    createTransaction: 'Crear Transacción',
    cashInflows: 'Efectivo Recibido (Ventas, etc.)',
    cashOutflows: 'Efectivo Pagado (Compras, Gastos)',
    expectedCashInRegister: 'Efectivo Esperado en Caja',
    openingBalance: 'Saldo Inicial',
    closingBalance: 'Saldo Final',
    cashIn: 'Efectivo Entrante',
    depositIn: 'Depósito Entrante',
    bankTransferIn: 'Transferencia Bancaria Entrante',
    cashOut: 'Efectivo Saliente',
    depositOut: 'Depósito Saliente',
    bankTransferOut: 'Transferencia Bancaria Saliente',
    totalIn: 'Total Entrante',
    totalOut: 'Total Saliente',
    partyEntity: 'Parte/Entidad',
    clientSupplierBank: 'Cliente/Proveedor/Banco',
    cost: 'Costo',
    costOfGoodsSold: 'Costo de Bienes Vendidos',
    
    // Fase 1 - Datos Maestros
    bankAccounts: 'Cuentas Bancarias',
    newBankAccount: 'Nueva Cuenta Bancaria',
    editBankAccount: 'Editar Cuenta Bancaria',
    accountType: 'Tipo de Cuenta',
    checking: 'Corriente',
    savings: 'Ahorros',
    location: 'Ubicación',
    cashRegisters: 'Cajas Registradoras',
    newCashRegister: 'Nueva Caja Registradora',
    editCashRegister: 'Editar Caja Registradora',
    cards: 'Tarjetas',
    newCard: 'Nueva Tarjeta',
    editCard: 'Editar Tarjeta',
    cardNumber: 'Número de Tarjeta',
    last4Digits: 'Últimos 4 Dígitos',
    cardType: 'Tipo de Tarjeta',
    cardBrand: 'Marca de Tarjeta',
    cardName: 'Nombre de Tarjeta',
    financers: 'Financiadores',
    newFinancer: 'Nuevo Financiador',
    editFinancer: 'Editar Financiador',
    contactPerson: 'Persona de Contacto',
    email: 'Correo Electrónico',
    financerType: 'Tipo de Financiador',
    bank: 'Banco',
    investor: 'Inversionista',
    rnc: 'RNC',
    create: 'Crear',
    
    // Fase 3 - Actualizaciones de Caja
    selectCashRegister: 'Seleccionar Caja',
    selectBankAccount: 'Seleccionar Cuenta Bancaria',
    selectCustomer: 'Seleccionar Cliente',
    selectFinancer: 'Seleccionar Financiador',
    selectContributor: 'Seleccionar Contribuyente',
    selectLender: 'Seleccionar Prestamista',
    selectInvoices: 'Seleccionar Facturas',
    arCollection: 'Cobro de CxC',
    contribution: 'Aporte',
    loan: 'Préstamo',
    correction: 'Corrección',
    chequeNumber: 'Número de Cheque',
    receiptNumber: 'Número de Recibo',
    bankCheque: 'Cheque Bancario',
    pendingInvoices: 'Facturas Pendientes',
    transactionCreated: '¡Transacción creada exitosamente!',
    corrections: 'Correcciones',
    sale: 'Venta',
    netCashPosition: 'Posición Neta de Efectivo',
    
    // Fase 4 - Actualizaciones de Registro Bancario
    chequeTransferNumber: 'Cheque/Transferencia #',
    selectInvoicesToPay: 'Seleccionar Facturas a Pagar',
    selectedInvoicesTotal: 'Total de Facturas Seleccionadas',
    noPendingInvoicesForSupplier: 'No se encontraron facturas pendientes para este proveedor',
    
    // Traducciones faltantes de Registro Bancario
    fromAccountsPayable: 'De Cuentas por Pagar',
    creditPurchasePayment: 'Pago de Compra a Crédito',
    thisTransactionWillPay: 'Esta transacción pagará la deuda de compra a crédito. El formulario ha sido prellenado con los detalles del pago.',
    pleaseKeepTransactionType: 'Por favor mantenga el Tipo de Transacción como "SALIDA" para el pago.',
    pleaseSelectAtLeastOneInvoice: 'Por favor seleccione al menos una factura para pagar',
    deleteTransactionConfirm: '¿Está seguro de que desea eliminar esta transacción?',
    selectSpecificInvoices: 'Seleccione las facturas/compras específicas que desea pagar. Cada elemento muestra información detallada de la factura.',
    invoice: 'factura',
    invoicesLowercase: 'facturas',
    paymentColon: 'Pago:',
    all: 'Todos',
    // Traducciones faltantes de Cuentas por Pagar
    payableTo: 'Pagadero A',
    cardCompany: 'Compañía de Tarjeta',
    loadingAccountsPayable: 'Cargando cuentas por pagar',
    pleaseSelectCardForPayment: 'Por favor seleccione una tarjeta para el pago',
    paymentRecordedSuccessfully: 'Pago registrado exitosamente',
    recordingPayment: 'Registrando pago',
    updatingDeadline: 'Actualizando fecha límite',
    paymentForCreditPurchase: 'Pago por Compra a Crédito',
    creditPurchasePaymentType: 'Pago de Compra a Crédito',
    payViaBankButton: 'Pagar vía Banco',
    
    // Traducciones faltantes de Cuentas por Pagar
    selectDebitCard: 'Seleccionar Tarjeta de Débito',
    immediatePayment: 'Pago Inmediato',
    selectADebitCard: 'Seleccionar una tarjeta de débito...',
    debitCardExplanation: 'Tarjeta de DÉBITO: Dinero deducido del banco inmediatamente para pagar esta deuda',
    creditCardPayment: 'Pago con Tarjeta de Crédito',
    cardLabel: 'Tarjeta:',
    whatHappens: 'Qué sucede:',
    creditLimitRestored: 'El límite de crédito será restaurado por',
    noCardSelectionNeeded: 'No se necesita selección de tarjeta - el sistema usará automáticamente la tarjeta de crédito original.',
    confirmPaymentRestoreCredit: 'Confirmar Pago y Restaurar Crédito',
    
    // Traducciones adicionales faltantes
    saleDetails: 'Detalles de Venta',
    processCardPayment: 'Procesar Pago con Tarjeta',
    editProduct: 'Editar Producto',
    deleteProduct: 'Eliminar Producto',
    editNetwork: 'Editar Red',
    deleteNetwork: 'Eliminar Red',
    viewDepreciationSchedule: 'Ver Cronograma de Depreciación',
    ncfNumber: 'Número NCF',
    unitCostPlaceholder: 'Costo Unitario',
    allTypes: 'Todos los Tipos',
    debitNote: 'Nota de Débito',
    creditNote: 'Nota de Crédito',
    adjustment: 'Ajuste',
    debitNoteND: 'Nota de Débito (ND)',
    creditNoteNC: 'Nota de Crédito (NC)',
    adjustmentAJ: 'Ajuste (AJ)',
    creditSaleCollection: 'Cobro de Venta a Crédito',
  }
};

type Language = 'en' | 'es';
type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Get saved language from localStorage or default to English
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'es') ? saved : 'en';
  });

  // Save language preference to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  // Translation function
  const t = (key: TranslationKey): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
